# Generated by Django 4.2.6 on 2023-10-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploads/")),
                ("type", models.CharField(max_length=255)),
                ("size", models.IntegerField()),
                ("text", models.TextField()),
            ],
        ),
    ]
