export const Members = [
  
    {
      id: 1,
      name: "Adagala, Beatrice Kahai",
      constituency: "Vihiga (CWR)",
      party: "ANC",
    },
    {
      id: 2,
      name: "Denar, Joseph Hamisi",
      constituency: "Nominated",
      party: "ANC",
    },
    {
      id: 3,
      name: "Gimose, Charles Gumini",
      constituency: "Hamisi",
      party: "ANC",
    },
    {
      id: 4,
      name: "IkanaM, Frederick Lusuli",
      constituency: "Shinyalu",
      party: "ANC",
    },
    {
      id: 5,
      name: "Injendi, Moses Malulu",
      constituency: "Malava",
      party: "ANC",
    },
    {
      id: 6,
      name: "Kagesi, Kivai Ernest Ogesi",
      constituency: "Vihiga",
      party: "ANC",
    },
    {
      id: 7,
      name: "Omboko, Milemba Jeremiah",
      constituency: "Emuhaya",
      party: "ANC",
    },
    {
      id: 8,
      name: "Tandaza, Kassim Sawa",
      constituency: "Matuga",
      party: "ANC",
    },
    {
      id: 9,
      name: "Koech, Victor Kipngetich",
      constituency: "Chepalungu",
      party: "CCM",
    },
    {
      id: 10,
      name: "Barasa, Patrick Simiyu",
      constituency: "Cherangany",
      party: "DAP-K",
    },
    {
      id: 11,
      name: "Bisau, Maurice Kakai",
      constituency: "Kiminini",
      party: "DAP-K",
    },
    {
      id: 12,
      name: "Oyugi, Dick Maungu",
      constituency: "Luanda",
      party: "DAP-K",
    },
    {
      id: 13,
      name: "Salasya, Peter Kalerwa",
      constituency: "Mumias East",
      party: "DAP-K",
    },
    {
      id: 14,
      name: "Wamboka, Nelson Jack Wamboka",
      constituency: "Bumula",
      party: "DAP-K",
    },
    {
      id: 15,
      name: "Ruku, Geoffrey Kariuki Kiringa",
      constituency: "Mbeere North",
      party: "DP",
    },
    {
      id: 16,
      name: "Kalasinga, Joseph Simiyu Wekesa Majimbo",
      constituency: "Kabuchai",
      party: "FORD-K",
    },
    {
      id: 17,
      name: "Makali, John Okwisia",
      constituency: "Kanduyi",
      party: "FORD-K",
    },
    {
      id: 18,
      name: "Murumba, John Chikati",
      constituency: "Tongaren",
      party: "FORD-K",
    },
    {
      id: 19,
      name: "Wambilianga, Catherine Nanjala",
      constituency: "Busia (CWR)",
      party: "FORD-K",
    },
    {
      id: 20,
      name: "Wanyonyi, Ferdinand Kevin",
      constituency: "Kwanza",
      party: "FORD-K",
    },
    {
      id: 21,
      name: "Wanyonyi, Martin Pepela",
      constituency: "Webuye West",
      party: "FORD-K",
    },
    {
      id: 22,
      name: "Muli, Fabian Kyule",
      constituency: "Kangundo",
      party: "GDDP",
    },
    {
      id: 23,
      name: "Abdul, Rahim Dawood",
      constituency: "North Imenti",
      party: "Independent",
    },
    {
      id: 24,
      name: "Ahmed, Shakeel Ahmed Shabbir",
      constituency: "Kisumu East",
      party: "Independent",
    },
    {
      id: 25,
      name: "Caroline, Jeptoo Ng’elechei",
      constituency: "Elgeyo Marakwet (CWR)",
      party: "Independent",
    },
    {
      id: 26,
      name: "Karauri, Ronald Kamwiko",
      constituency: "Kasarani",
      party: "Independent",
    },
    {
      id: 27,
      name: "Kitilai, Ole Ntutu",
      constituency: "Narok South",
      party: "Independent",
    },
    {
      id: 28,
      name: "Kururia, Elijah Njore Njoroge",
      constituency: "Gatundu North",
      party: "Independent",
    },
    {
      id: 29,
      name: "Marubu, Monicah Muthoni",
      constituency: "Lamu (CWR)",
      party: "Independent",
    },
    {
      id: 30,
      name: "Mohammed, Fatuma Zainabu",
      constituency: "Migori (CWR)",
      party: "Independent",
    },
    {
      id: 31,
      name: "Mulanya, Geoffrey Ekesa",
      constituency: "Nambale",
      party: "Independent",
    },
    {
      id: 32,
      name: "Mwalyo, Joshua Mbithi Mutua",
      constituency: "Masinga",
      party: "Independent",
    },
    {
      id: 33,
      name: "Nebart, Bernard Muriuki",
      constituency: "Mbeere South",
      party: "Independent",
    },
    {
      id: 34,
      name: "Toroitich, Timothy Kipchumba",
      constituency: "Marakwet West",
      party: "Independent",
    },
    {
      id: 35,
      name: "Abdirahman, Mohamed Abdi",
      constituency: "Lafey",
      party: "JP",
    },
    {
      id: 36,
      name: "Arama, Samuel",
      constituency: "Nakuru Town West",
      party: "JP",
    },
    {
      id: 37,
      name: "Bonaya, Mumina Gollo",
      constituency: "Isiolo (CWR)",
      party: "JP",
    },
    {
      id: 38,
      name: "Chege, Sabina Wanjiru",
      constituency: "Nominated",
      party: "JP",
    },
    {
      id: 39,
      name: "Hassan, Abdi Yusuf",
      constituency: "Kamkunji",
      party: "JP",
    },
    {
      id: 40,
      name: "Ithinji, Dr. Shadrack Mwiti",
      constituency: "South Imenti",
      party: "JP",
    },
    {
      id: 41,
      name: "Karitho, Kiili Daniel",
      constituency: "Igembe Central",
      party: "JP",
    },
    {
      id: 42,
      name: "Kiaraho, David Njuguna",
      constituency: "Ol Kalou",
      party: "JP",
    },
    {
      id: 43,
      name: "Korere, Sarah Paulata",
      constituency: "Laikipia North",
      party: "JP",
    },
    {
      id: 44,
      name: "Koyi, John Waluke",
      constituency: "Sirisia",
      party: "JP",
    },
    {
      id: 45,
      name: "Kwenya, Thuku Zachary",
      constituency: "Kinangop",
      party: "JP",
    },
    {
      id: 46,
      name: "Lomwa, Joseph Samal",
      constituency: "Isiolo North",
      party: "JP",
    },
    {
      id: 47,
      name: "Maina, Mwago Amos",
      constituency: "Starehe",
      party: "JP",
    },
    {
      id: 48,
      name: "Mogaka, Stephen M.",
      constituency: "West Mugirango",
      party: "JP",
    },
    {
      id: 49,
      name: "Mohamed, Aden Daudi",
      constituency: "Wajir East",
      party: "JP",
    },
    {
      id: 50,
      name: "Mongina, Jerusha Momanyi",
      constituency: "Nyamira (CWR)",
      party: "JP",
    },
    {
      id: 51,
      name: "Mrembo, Irene Njoki",
      constituency: "Bahati",
      party: "JP",
    },
    {
      id: 52,
      name: "Muiruri, Muthama Stanley",
      constituency: "Lamu West",
      party: "JP",
    },
    {
      id: 53,
      name: "Mwenje, Mark Samuel Muriithi",
      constituency: "Embakasi West",
      party: "JP",
    },
    {
      id: 54,
      name: "Ngikolong, Nicholas Ng’ikor Nixon",
      constituency: "Turkana East",
      party: "JP",
    },
    {
      id: 55,
      name: "Nyamai, Rachael Kaki",
      constituency: "Kitui South",
      party: "JP",
    },
    {
      id: 56,
      name: "Obo, Ruweida Mohamed",
      constituency: "Lamu East",
      party: "JP",
    },
    {
      id: 57,
      name: "Pareiyo, Agnes Mantaine",
      constituency: "Narok North",
      party: "JP",
    },
    {
      id: 58,
      name: "Shake, Peter Mbogho",
      constituency: "Mwatate",
      party: "JP",
    },
    {
      id: 59,
      name: "Shurie, Abdi Omar",
      constituency: "Balambala",
      party: "JP",
    },
    {
      id: 60,
      name: "Siyad, Amina Udgoon",
      constituency: "Garissa (CWR)",
      party: "JP",
    },
    {
      id: 61,
      name: "Tubi, Bidu Mohamed",
      constituency: "Isiolo South",
      party: "JP",
    },
    {
      id: 62,
      name: "Wehliye, Adan Keynan",
      constituency: "Eldas",
      party: "JP`",
    },
    {
      id: 63,
      name: "Abdullahi, Amina Dika",
      constituency: "Tana River (CWR)",
      party: "KANU",
    },
    {
      id: 64,
      name: "Guyo, Adhe Wario",
      constituency: "North Horr",
      party: "KANU",
    },
    {
      id: 65,
      name: "Kassait, William Kamket",
      constituency: "Tiaty",
      party: "KANU",
    },
    {
      id: 66,
      name: "Lentoijoni, Jackson Lekumontare",
      constituency: "Samburu East",
      party: "KANU",
    },
    {
      id: 67,
      name: "Lesuuda, Josephine Naisula",
      constituency: "Samburu West",
      party: "KANU",
    },
    {
      id: 68,
      name: "Sunkuli, Julius Lekakeny Ole",
      constituency: "Kilgoris",
      party: "KANU",
    },
    {
      id: 69,
      name: "Kasiwai, Rael Chepkemoi",
      constituency: "West Pokot (CWR)",
      party: "KUP",
    },
    {
      id: 70,
      name: "Pkosing, David Losiakou",
      constituency: "Pokot South",
      party: "KUP",
    },
    {
      id: 71,
      name: "Titus, Lotee",
      constituency: "Kacheliba",
      party: "KUP",
    },
    {
      id: 72,
      name: "Mule, Caleb Mutiso",
      constituency: "Machakos Town",
      party: "MCCP",
    },
    {
      id: 73,
      name: "Mutuse, Eckomas Mwengi",
      constituency: "Kibwezi West",
      party: "MCCP",
    },
    {
      id: 74,
      name: "Ochieng, David Ouma",
      constituency: "Ugenya",
      party: "MDG",
    },
    {
      id: 75,
      name: "Abdi, Abdi Ali",
      constituency: "Ijara",
      party: "NAP-K",
    },
    {
      id: 76,
      name: "Aburi, Lawrence Mpuru",
      constituency: "Tigania East",
      party: "NOPEU",
    },
    {
      id: 77,
      name: "Abdirahman, Husseinweytan Mohamed",
      constituency: "Mandera East",
      party: "ODM",
    },
    {
      id: 78,
      name: "Abuor, Paul",
      constituency: "Rongo",
      party: "ODM",
    },
    {
      id: 79,
      name: "Adow, Mohamed Aden",
      constituency: "Wajir South",
      party: "ODM",
    },
    {
      id: 80,
      name: "Amollo, Paul Otiende",
      constituency: "Rarieda",
      party: "ODM",
    },
    {
      id: 81,
      name: "Samuel Onunga",
      constituency: "Alego Usonga",
      party: "ODM",
    },
    {
      id: 82,
      name: "Bady, Bady Twalib",
      constituency: "Jomvu",
      party: "ODM",
    },
    {
      id: 83,
      name: "Barongo, Nolfason Obadiah",
      constituency: "Bomachoge Borabu",
      party: "ODM",
    },
    {
      id: 84,
      name: "Bedzimba, Rashid Juma",
      constituency: "Kisauni",
      party: "ODM",
    },
    {
      id: 85,
      name: "Busia, Ruth Adhiambo Odinga",
      constituency: "Kisumu (CWR)",
      party: "ODM",
    },
    {
      id: 86,
      name: "Buyu, Rozaah Akinyi",
      constituency: "Kisumu West",
      party: "ODM",
    },
    {
      id: 87,
      name: "Chimba, Zamzam Mohamed",
      constituency: "Mombasa (CWR)",
      party: "ODM",
    },
    {
      id: 88,
      name: "Elachi, Beatrice Kadeveresia",
      constituency: "Dagoretti North",
      party: "ODM",
    },
    {
      id: 89,
      name: "Farah, Yussuf Mohamed",
      constituency: "Wajir West",
      party: "ODM",
    },
    {
      id: 90,
      name: "Francis, Kajwang’ Tom Joseph",
      constituency: "Ruaraka",
      party: "ODM",
    },
    {
      id: 91,
      name: "Gisairo, Clive Ombane",
      constituency: "Kitutu Masaba",
      party: "ODM",
    },
    {
      id: 92,
      name: "Gogo, Lilian Achieng",
      constituency: "Rangwe",
      party: "ODM",
    },
    {
      id: 93,
      name: "Guyo, Ali Wario",
      constituency: "Garsen",
      party: "ODM",
    },
    {
      id: 94,
      name: "Hamisi, Kakuta Maimai",
      constituency: "Kajiado East",
      party: "ODM",
    },
    {
      id: 95,
      name: "Hiribae, Said Buya",
      constituency: "Galole",
      party: "ODM",
    },
    {
      id: 96,
      name: "Jehow, Fatuma Abdi",
      constituency: "Wajir (CWR)",
      party: "ODM",
    },
    {
      id: 97,
      name: "Kaluma, George Peter Opondo",
      constituency: "Homa Bay Town",
      party: "ODM",
    },
    {
      id: 98,
      name: "Kanchory, Elijah Memusi",
      constituency: "Kajiado Central",
      party: "ODM",
    },
    {
      id: 99,
      name: "Katana, Paul Kahindi",
      constituency: "Kaloleni",
      party: "ODM",
    },
    {
      id: 100,
      name: "Khodhe, Phelix Odiwuor",
      constituency: "Langata",
      party: "ODM",
    },
    {
      id: 101,
      name: "Kibagendi, Antoney",
      constituency: "Kitutu Chache South",
      party: "ODM",
    },
    {
      id: 102,
      name: "Kiti, Richard Ken Chonga",
      constituency: "Kilifi South",
      party: "ODM",
    },
    {
      id: 103,
      name: "Kombe, Harrison Garama",
      constituency: "Magarini",
      party: "ODM",
    },
    {
      id: 104,
      name: "Luyai, Caleb Amisi",
      constituency: "Saboti",
      party: "ODM",
    },
    {
      id: 105,
      name: "Machele, Mohamed Soud",
      constituency: "Mvita",
      party: "ODM",
    },
    {
      id: 106,
      name: "Manduku, Daniel Ogwoka",
      constituency: "Nyaribari Masaba",
      party: "ODM",
    },
    {
      id: 107,
      name: "Masara, Peter Francis",
      constituency: "Suna West",
      party: "ODM",
    },
    {
      id: 108,
      name: "Masito, Fatuma Hamisi",
      constituency: "Kwale (CWR)",
      party: "ODM",
    },
    {
      id: 109,
      name: "Mayaka, Irene Nyakerario",
      constituency: "Nominated",
      party: "ODM",
    },
    {
      id: 110,
      name: "Mboko, Mishi Juma Khamisi",
      constituency: "Likoni",
      party: "ODM",
    },
    {
      id: 111,
      name: "Mohamed, Abdikadir Hussein",
      constituency: "Lagdera",
      party: "ODM",
    },
    {
      id: 112,
      name: "Mohamed, Junet Sheikh Nuh",
      constituency: "Suna East",
      party: "ODM",
    },
    {
      id: 113,
      name: "Mohamed, Umulkher Harun",
      constituency: "Nominated",
      party: "ODM",
    },
    {
      id: 114,
      name: "Mugabe, Innocent Maino",
      constituency: "Likuyani",
      party: "ODM",
    },
    {
      id: 115,
      name: "Muhanda, Elsie Busihile",
      constituency: "Kakamega (CWR)",
      party: "ODM",
    },
    {
      id: 116,
      name: "Mukhwana, Titus Khamala",
      constituency: "Lurambi",
      party: "ODM",
    },
    {
      id: 117,
      name: "Mwale, Nicholas S. Tindi",
      constituency: "Butere",
      party: "ODM",
    },
    {
      id: 118,
      name: "Mwanyanje, Gertrude Mbeyu",
      constituency: "Kilifi (CWR)",
      party: "ODM",
    },
    {
      id: 119,
      name: "Mnyazi, Amina Laura",
      constituency: "Malindi",
      party: "ODM",
    },
    {
      id: 120,
      name: "Nabii, Nabwera Daraja",
      constituency: "Lugari",
      party: "ODM",
    },
    {
      id: 121,
      name: "Nabulindo, Peter Oscar",
      constituency: "Matungu",
      party: "ODM",
    },
    {
      id: 122,
      name: "Naibun, Paul Ekwom",
      constituency: "Turkana North",
      party: "ODM",
    },
    {
      id: 123,
      name: "Naicca, Johnson Manya",
      constituency: "Mumias West",
      party: "ODM",
    },
    {
      id: 124,
      name: "Namoit, John Ariko",
      constituency: "Turkana South",
      party: "ODM",
    },
    {
      id: 125,
      name: "Ng’ongo, John Mbadi",
      constituency: "Nominated",
      party: "ODM",
    },
    {
      id: 126,
      name: "Nyamita, Mark Ogolla",
      constituency: "Uriri",
      party: "ODM",
    },
    {
      id: 127,
      name: "Nyikal, James Wambura",
      constituency: "Seme",
      party: "ODM",
    },
    {
      id: 128,
      name: "Obara, Eve Akinyi",
      constituency: "Kabondo Kasipul",
      party: "ODM",
    },
    {
      id: 129,
      name: "Odanga, Geoffrey Makokha",
      constituency: "Matayos",
      party: "ODM",
    },
    {
      id: 130,
      name: "Odege, Tom Mboya",
      constituency: "Nyatike",
      party: "ODM",
    },
    {
      id: 131,
      name: "Odhiambo, Elisha Ochieng",
      constituency: "Gem",
      party: "ODM",
    },
    {
      id: 132,
      name: "Odhiambo, Millie Grace Akoth",
      constituency: "Suba North",
      party: "ODM",
    },
    {
      id: 133,
      name: "Odoyo, Okello Jared",
      constituency: "Nyando",
      party: "ODM",
    },
    {
      id: 134,
      name: "Oduor, Christine Ombaka",
      constituency: "Siaya (CWR)",
      party: "ODM",
    },
    {
      id: 135,
      name: "Ogolla, Gideon Ochanda",
      constituency: "Bondo",
      party: "ODM",
    },
    {
      id: 136,
      name: "Oku, Edward Kaunya",
      constituency: "Teso North",
      party: "ODM",
    },
    {
      id: 137,
      name: "Okuome, Andrew Adipo",
      constituency: "Karachuonyo",
      party: "ODM",
    },
    {
      id: 138,
      name: "Oluoch, Anthony Tom",
      constituency: "Mathare",
      party: "ODM",
    },
    {
      id: 139,
      name: "Omanyo, Catherine Nakhabi",
      constituency: "Busia (CWR)",
      party: "ODM",
    },
    {
      id: 140,
      name: "Omondi, Caroli",
      constituency: "Suba South",
      party: "ODM",
    },
    {
      id: 141,
      name: "Omwera, George Aladwa",
      constituency: "Makadara",
      party: "ODM",
    },
    {
      id: 142,
      name: "Ongili, Babu Owino Paul",
      constituency: "Embakasi East",
      party: "ODM",
    },
    {
      id: 143,
      name: "Orero, Peter Ochieng",
      constituency: "Kibra",
      party: "ODM",
    },
    {
      id: 144,
      name: "Oron, Joshua Odongo",
      constituency: "Kisumu Central",
      party: "ODM",
    },
    {
      id: 145,
      name: "Osero, Patrick Kibagendi",
      constituency: "Borabu",
      party: "ODM",
    },
    {
      id: 146,
      name: "Osogo, Bensuda Joyce Atieno",
      constituency: "Homa Bay (CWR)",
      party: "ODM",
    },
    {
      id: 147,
      name: "Oundo, Wilberforce Ojiambo",
      constituency: "Funyula",
      party: "ODM",
    },
    {
      id: 148,
      name: "Owino, John Walter",
      constituency: "Awendo",
      party: "ODM",
    },
    {
      id: 149,
      name: "Owino, Martin Peters",
      constituency: "Ndhiwa",
      party: "ODM",
    },
    {
      id: 150,
      name: "Owuor, Joshua Aduma",
      constituency: "Nyakach",
      party: "ODM",
    },
    {
      id: 151,
      name: "Oyoo, James Onyango",
      constituency: "Muhoroni",
      party: "ODM",
    },
    {
      id: 152,
      name: "Oyula, Joseph H. Maero",
      constituency: "Butula",
      party: "ODM",
    },
    {
      id: 153,
      name: "Passaris, Esther Muthomi",
      constituency: "Nairobi City (CWR)",
      party: "ODM",
    },
    {
      id: 154,
      name: "Sakimba, Parashina Samuel",
      constituency: "Kajiado South",
      party: "ODM",
    },
    {
      id: 155,
      name: "Shimbwa, Omar Mwinyi",
      constituency: "Changamwe",
      party: "ODM",
    },
    {
      id: 156,
      name: "Shinali, Bernard Masaka",
      constituency: "Ikolomani",
      party: "ODM",
    },
    {
      id: 157,
      name: "Wandayi, James Opiyo",
      constituency: "Ugunja",
      party: "ODM",
    },
    {
      id: 158,
      name: "Wangaya, Christopher Aseka",
      constituency: "Khwisero",
      party: "ODM",
    },
    {
      id: 159,
      name: "Wangwe, Emmanuel",
      constituency: "Navakholo",
      party: "ODM",
    },
    {
      id: 160,
      name: "Wanjala, Raphael Sauti Bitta",
      constituency: "Budalangi",
      party: "ODM",
    },
    {
      id: 161,
      name: "Were, Charles Ong’ondo",
      constituency: "Kasipul",
      party: "ODM",
    },
    {
      id: 162,
      name: "Wetangula, Timothy Wanyonyi",
      constituency: "Westlands",
      party: "ODM",
    },
    {
      id: 163,
      name: "Mupe, Anthony Kenga",
      constituency: "Rabai",
      party: "PAA",
    },
    {
      id: 164,
      name: "Rai, Samuel Gonzi",
      constituency: "Kinango",
      party: "PAA",
    },
    {
      id: 165,
      name: "Tungule, Charo Kenneth Kazungu",
      constituency: "Ganze",
      party: "PAA",
    },
    {
      id: 166,
      name: "Kiunjuri, Festus Mwangi",
      constituency: "Laikipia East",
      party: "TSP",
    },
    {
      id: 167,
      name: "Nduyo, Susan Ngugi",
      constituency: "Tharaka-Nithi(CWR)",
      party: "TSP",
    },
    {
      id: 168,
      name: "Akuja, Protus Ewesit",
      constituency: "Loima",
      party: "UDA",
    },
    {
      id: 169,
      name: "Alfah, Miruka Ondieki",
      constituency: "Bomachoge Chache",
      party: "UDA",
    },
    {
      id: 170,
      name: "Ali, Abdisirat Khalif",
      constituency: "Nominated",
      party: "UDA",
    },
    {
      id: 171,
      name: "Bader, Salim Feisal",
      constituency: "Msambweni",
      party: "UDA",
    },
    {
      id: 172,
      name: "Barre, Hussein Abdi",
      constituency: "Tarbaj",
      party: "UDA",
    },
    {
      id: 173,
      name: "Barrow, Dekow Mohamed",
      constituency: "Garissa Township",
      party: "UDA",
    },
    {
      id: 174,
      name: "Bartoo, Phylis Jepkemoi",
      constituency: "Moiben",
      party: "UDA",
    },
    {
      id: 175,
      name: "Baya, Owen Yaa",
      constituency: "Kilifi North",
      party: "UDA",
    },
    {
      id: 176,
      name: "Biego, Paul Kibichy",
      constituency: "Chesumei",
      party: "UDA",
    },
    {
      id: 177,
      name: "Bowen, David Kangogo",
      constituency: "Marakwet East",
      party: "UDA",
    },
    {
      id: 178,
      name: "Chebor, Paul Kibet",
      constituency: "Rongai",
      party: "UDA",
    },
    {
      id: 179,
      name: "Chege, John Kiragu",
      constituency: "Limuru",
      party: "UDA",
    },
    {
      id: 180,
      name: "Chelule, Liza Chepkorir",
      constituency: "Nakuru (CWR)",
      party: "UDA",
    },
    {
      id: 181,
      name: "Chepkonga, Kiprono Samwel",
      constituency: "Ainabkoi",
      party: "UDA",
    },
    {
      id: 182,
      name: "Chepkorir, Linet",
      constituency: "Bomet (CWR)",
      party: "UDA",
    },
    {
      id: 183,
      name: "Chepkwony, Charity Kathambi",
      constituency: "Njoro",
      party: "UDA",
    },
    {
      id: 184,
      name: "Cherorot, Joseph Kimutai",
      constituency: "Kipkelion East",
      party: "UDA",
    },
    {
      id: 185,
      name: "Chesebe, Fred Kapondi",
      constituency: "Mt. Elgon",
      party: "UDA",
    },
    {
      id: 186,
      name: "Chumel, Samwel Moroto",
      constituency: "Kapenguria",
      party: "UDA",
    },
    {
      id: 187,
      name: "Double N, Pamela Njoki Njeru",
      constituency: "Embu (CWR)",
      party: "UDA",
    },
    {
      id: 188,
      name: "Emathe, Joseph Namuar",
      constituency: "Turkana Central",
      party: "UDA",
    },
    {
      id: 189,
      name: "Gachagua, George N.",
      constituency: "Ndaragwa",
      party: "UDA",
    },
    {
      id: 190,
      name: "Gachobe, Samuel Kinuthia",
      constituency: "Subukia",
      party: "UDA",
    },
    {
      id: 191,
      name: "Gakuya, James Mwangi",
      constituency: "Embakasi North",
      party: "UDA",
    },
    {
      id: 192,
      name: "Gathiru, Mejjadonk Benjamin",
      constituency: "Embakasi Central",
      party: "UDA",
    },
    {
      id: 193,
      name: "Gichohi, Kaguchia John Philip",
      constituency: "Mukurweini",
      party: "UDA",
    },
    {
      id: 194,
      name: "Gichuki, Edwin Mugo",
      constituency: "Mathioya",
      party: "UDA",
    },
    {
      id: 195,
      name: "Gikaria, David",
      constituency: "Nakuru Town East",
      party: "UDA",
    },
    {
      id: 196,
      name: "Gitari, Joseph Gachoki",
      constituency: "Kirinyaga Central",
      party: "UDA",
    },
    {
      id: 197,
      name: "Gitau, Faith Wairimu",
      constituency: "Nyandarua (CWR)",
      party: "UDA",
    },
    {
      id: 198,
      name: "Githinji, Robert Gichimu",
      constituency: "Gichugu",
      party: "UDA",
    },
    {
      id: 199,
      name: "GK, George Macharia Kariuki",
      constituency: "Ndia",
      party: "UDA",
    },
    {
      id: 200,
      name: "Ichung’wah, Anthony Kimani",
      constituency: "Kikuyu",
      party: "UDA",
    },
    {
      id: 201,
      name: "Ikiara, Dorothy Muthoni",
      constituency: "Nominated",
      party: "UDA",
    },
    {
      id: 202,
      name: "Iraya, Joseph Wainaina",
      constituency: "Nominated",
      party: "UDA",
    },
    {
      id: 203,
      name: "Jhanda Zaheer",
      constituency: "Nyaribari Chache",
      party: "UDA",
    },
    {
      id: 204,
      name: "Kagiri, Jane Wangechi",
      constituency: "Laikipia (CWR)",
      party: "UDA",
    },
    {
      id: 205,
      name: "Kagombe, Gabriel Gathuka",
      constituency: "Gatundu South",
      party: "UDA",
    },
    {
      id: 206,
      name: "Kahangara, Joseph Mburu",
      constituency: "Lari",
      party: "UDA",
    },
    {
      id: 207,
      name: "Kahugu, Eric Meangi",
      constituency: "Mathira",
      party: "UDA",
    },
    {
      id: 208,
      name: "Kailema, Elizabeth Karambu",
      constituency: "Meru (CWR)",
      party: "UDA",
    },
    {
      id: 209,
      name: "Kamuren, Charles",
      constituency: "Baringo South",
      party: "UDA",
    },
    {
      id: 210,
      name: "Kandie, Joshua Chepyegon",
      constituency: "Baringo Central",
      party: "UDA",
    },
    {
      id: 211,
      name: "Karani, Stephen Wachira",
      constituency: "Laikipia West",
      party: "UDA",
    },
    {
      id: 212,
      name: "Karemba, Eric Muchangi Njiru",
      constituency: "Runyenjes",
      party: "UDA",
    },
    {
      id: 213,
      name: "Kemei, Beatrice Chepng’eno",
      constituency: "Kericho (CWR)",
      party: "UDA",
    },
    {
      id: 214,
      name: "Kemei, Justice Kipsang",
      constituency: "Sigowet/Soin",
      party: "UDA",
    },
    {
      id: 215,
      name: "Kemero, Maisori Marwa Kitayama",
      constituency: "Kuria East",
      party: "UDA",
    },
    {
      id: 216,
      name: "Kihara, Jayne Wanjiru Njeru",
      constituency: "Naivasha",
      party: "UDA",
    },
    {
      id: 217,
      name: "Kihungi, Peter Irungu",
      constituency: "Kangema",
      party: "UDA",
    },
    {
      id: 218,
      name: "Kilel, Richard Cheruiyot",
      constituency: "Bomet Central",
      party: "UDA",
    },
    {
      id: 219,
      name: "Kimani, Francis Kuria",
      constituency: "Molo",
      party: "UDA",
    },
    {
      id: 220,
      name: "Kingara, Simon Ng’ang’a",
      constituency: "Ruiru",
      party: "UDA",
    },
    {
      id: 221,
      name: "Kipbiwot, Julius Melly",
      constituency: "Tinderet",
      party: "UDA",
    },
    {
      id: 222,
      name: "Kipgnor, Reuben Kiborek",
      constituency: "Mogotio",
      party: "UDA",
    },
    {
      id: 223,
      name: "Kipkoech, Gideon Kimaiyo",
      constituency: "Keiyo South",
      party: "UDA",
    },
    {
      id: 224,
      name: "Kipkoros, Joseph Makilap",
      constituency: "Baringo North",
      party: "UDA",
    },
    {
      id: 225,
      name: "Kiplagat, David",
      constituency: "Soy",
      party: "UDA",
    },
    {
      id: 226,
      name: "Kiprono, Mutai Alfred",
      constituency: "Kuresoi North",
      party: "UDA",
    },
    {
      id: 227,
      name: "Kipyegon, Johana Ng’eno",
      constituency: "Emurua Dikirr",
      party: "UDA",
    },
    {
      id: 228,
      name: "Kirima, Moses Nguchine",
      constituency: "Central Imenti",
      party: "UDA",
    },
    {
      id: 229,
      name: "Kirwa, Abraham Kipsang",
      constituency: "Mosop",
      party: "UDA",
    },
    {
      id: 230,
      name: "Kitany, Marianne Jebet",
      constituency: "Aldai",
      party: "UDA",
    },
    {
      id: 231,
      name: "Kitur, Bernard Kibor",
      constituency: "Nandi Hills",
      party: "UDA",
    },
    {
      id: 232,
      name: "Koech, Nelson",
      constituency: "Belgut",
      party: "UDA",
    },
    {
      id: 233,
      name: "Komingoi, Kibet Kirui",
      constituency: "Bureti",
      party: "UDA",
    },
    {
      id: 234,
      name: "Korir, Adams Kipsanai",
      constituency: "Keiyo North",
      party: "UDA",
    },
    {
      id: 235,
      name: "Kosgei, Hilary Kiplangat",
      constituency: "Kipkelion West",
      party: "UDA",
    },
    {
      id: 236,
      name: "Kosgei, Jackson Kipkemoi",
      constituency: "Nominated",
      party: "UDA",
    },
    {
      id: 237,
      name: "Langat, Benjamin Kipkirui",
      constituency: "Ainamoi",
      party: "UDA",
    },
    {
      id: 238,
      name: "Lelmengit, Josses Kiptoo Kosgey",
      constituency: "Emgwen",
      party: "UDA",
    },
    {
      id: 239,
      name: "Lemanken, Aramat",
      constituency: "Narok East",
      party: "UDA",
    },
    {
      id: 240,
      name: "Lenguris, Pauline",
      constituency: "Samburu (CWR)",
      party: "UDA",
    },
    {
      id: 241,
      name: "Letipila, Dominic Eli",
      constituency: "Samburu North",
      party: "UDA",
    },
    {
      id: 242,
      name: "Lochakapong, Peter",
      constituency: "Sigor",
      party: "UDA",
    },
    {
      id: 243,
      name: "Logova, Sloya Clement",
      constituency: "Sabatia",
      party: "UDA",
    },
    {
      id: 244,
      name: "M’Anaiba, Julius Taitumu",
      constituency: "Igembe North",
      party: "UDA",
    },
    {
      id: 245,
      name: "Maina, Betty Njeri",
      constituency: "Murang’a (CWR)",
      party: "UDA",
    },
    {
      id: 246,
      name: "Maina, Jane Njeri",
      constituency: "Kirinyaga (CWR)",
      party: "UDA",
    },
    {
      id: 247,
      name: "Maingi, Mary",
      constituency: "Mwea",
      party: "UDA",
    },
    {
      id: 248,
      name: "Mathenge, Duncan Maina",
      constituency: "Nyeri Town",
      party: "UDA",
    },
    {
      id: 249,
      name: "Mbai, Nimrod Mbithuka",
      constituency: "Kitui East",
      party: "UDA",
    },
    {
      id: 250,
      name: "Mbiuki, Japhet Miriti Kareke",
      constituency: "Maara",
      party: "UDA",
    },
    {
      id: 251,
      name: "Mizighi, Lydia Haika Mnene",
      constituency: "Taita Taveta (CWR)",
      party: "UDA",
    },
    {
      id: 252,
      name: "Mohamed, Mohamed Ali",
      constituency: "Nyali",
      party: "UDA",
    },
    {
      id: 253,
      name: "Mokaya, Nyakundi Japheth",
      constituency: "Kitutu Chache North",
      party: "UDA",
    },
    {
      id: 254,
      name: "Muchira, Michael Mwangi",
      constituency: "Ol Jorok",
      party: "UDA",
    },
    {
      id: 255,
      name: "Muge, Cynthia Jepkosgei",
      constituency: "Nandi (CWR)",
      party: "UDA",
    },
    {
      id: 256,
      name: "Muhia, Wanjiku",
      constituency: "Kipipiri",
      party: "UDA",
    },
    {
      id: 257,
      name: "Mukunji, John Gitonga Mwaniki",
      constituency: "Manyatta",
      party: "UDA",
    },
    {
      id: 258,
      name: "Munyoro, Joseph Kamau",
      constituency: "Kigumo",
      party: "UDA",
    },
    {
      id: 259,
      name: "Muratha, Anne Wanjiku Mugo",
      constituency: "Kiambu (CWR)",
      party: "UDA",
    },
    {
      id: 260,
      name: "Muriu, Wakili Edward",
      constituency: "Gatanga",
      party: "UDA",
    },
    {
      id: 261,
      name: "Murugara, George Gitonga",
      constituency: "Tharaka",
      party: "UDA",
    },
    {
      id: 262,
      name: "Murwithania, Rindikiri Mugambi",
      constituency: "Buuri",
      party: "UDA",
    },
    {
      id: 263,
      name: "Musau, Vincent Musyoka",
      constituency: "Mwala",
      party: "UDA",
    },
    {
      id: 264,
      name: "Mutua, Didmus Wekesa Barasa",
      constituency: "Kimilili",
      party: "UDA",
    },
    {
      id: 265,
      name: "Mutunga, John Kanyuithia",
      constituency: "Tigania West",
      party: "UDA",
    },
    {
      id: 266,
      name: "Mwafrika, Augustine Kamande",
      constituency: "Royasambu",
      party: "UDA",
    },
    {
      id: 267,
      name: "Mwangi, Geoffrey Wandeto",
      constituency: "Tetu",
      party: "UDA",
    },
    {
      id: 268,
      name: "Mwangi, Teresia Wanjiru",
      constituency: "Nominated",
      party: "UDA",
    },
    {
      id: 269,
      name: "Mwiring, John Paul",
      constituency: "Igembe South",
      party: "UDA",
    },
    {
      id: 270,
      name: "Nanok, Daniel Epuyo",
      constituency: "Turkana West",
      party: "UDA",
    },
    {
      id: 271,
      name: "Ndung’u George Koimburi",
      constituency: "Juja",
      party: "UDA",
    },
    {
      id: 272,
      name: "Ng’ang’a Alice Wambui",
      constituency: "Thika Town",
      party: "UDA",
    },
    {
      id: 273,
      name: "Ngitit, Cecilia Asinyen",
      constituency: "Turkana (CWR)",
      party: "UDA",
    },
    {
      id: 274,
      name: "Nguro, Onesmus Ngogoyo",
      constituency: "Kajiado North",
      party: "UDA",
    },
    {
      id: 275,
      name: "Njoroge, Mary Wamaua Waithira",
      constituency: "Maragwa",
      party: "UDA",
    },
    {
      id: 276,
      name: "Njuguna, Chege",
      constituency: "Kandara",
      party: "UDA",
    },
    {
      id: 277,
      name: "Ntwiga, Patrick Munene",
      constituency: "Chuka/Igambang’ombe",
      party: "UDA",
    },
    {
      id: 278,
      name: "Nyamoko, Joash Nyamache",
      constituency: "North Mugirango",
      party: "UDA",
    },
    {
      id: 279,
      name: "Nyoro, Samson Ndindi",
      constituency: "Kiharu",
      party: "UDA",
    },
    {
      id: 280,
      name: "Onyiego, Silvanus Osoro",
      constituency: "South Mugirango",
      party: "UDA",
    },
    {
      id: 281,
      name: "Otucho, Mary Emaase",
      constituency: "Teso South",
      party: "UDA",
    },
    {
      id: 282,
      name: "Pukose, Robert (Dr.)",
      constituency: "Endebess",
      party: "UDA",
    },
    {
      id: 283,
      name: "Raso, Dido Ali",
      constituency: "Saku",
      party: "UDA",
    },
    {
      id: 284,
      name: "Risa, Sunkuiya George",
      constituency: "Kajiado West",
      party: "UDA",
    },
    {
      id: 285,
      name: "Robi, Mathias Nyamabe",
      constituency: "Kuria West",
      party: "UDA",
    },
    {
      id: 286,
      name: "Rutto, Julius Kipletting",
      constituency: "Kesses",
      party: "UDA",
    },
    {
      id: 287,
      name: "Saney, Ibrahim Abdi",
      constituency: "Wajir North",
      party: "UDA",
    },
    {
      id: 288,
      name: "Sankaire, Leah Sopiato",
      constituency: "Kajiado (CWR)",
      party: "UDA",
    },
    {
      id: 289,
      name: "Sergon, Flowrence Jematiah",
      constituency: "Baringo (CWR)",
      party: "UDA",
    },
    {
      id: 290,
      name: "Shollei, Gladys Jepkosgei Boss",
      constituency: "Uasin Gishu (CWR)",
      party: "UDA",
    },
    {
      id: 291,
      name: "Sigei, Francis Kipyegon arap",
      constituency: "Sotik",
      party: "UDA",
    },
    {
      id: 292,
      name: "Sirma, Musa Cherutich",
      constituency: "Eldama Ravine",
      party: "UDA",
    },
    {
      id: 293,
      name: "Sitati, Daniel Wanyama",
      constituency: "Webuye West",
      party: "UDA",
    },
    {
      id: 294,
      name: "Sitienei, Janet Jepkemboi",
      constituency: "Turbo",
      party: "UDA",
    },
    {
      id: 295,
      name: "Siyoi, Lillian Chebet",
      constituency: "Trans Nzoia (CWR)",
      party: "UDA",
    },
    {
      id: 296,
      name: "Sudi, Oscar Kipchumba",
      constituency: "Kapseret",
      party: "UDA",
    },
    {
      id: 297,
      name: "Tongoyo, Gabriel Koshal",
      constituency: "Narok West",
      party: "UDA",
    },
    {
      id: 298,
      name: "Tonkei, Rebecca Noonaishi",
      constituency: "Narok (CWR)",
      party: "UDA",
    },
    {
      id: 299,
      name: "Tonui, Joseph Kipkosgei",
      constituency: "Kuresoi South",
      party: "UDA",
    },
    {
      id: 300,
      name: "Wachira, Rahab Mukami",
      constituency: "Nyeri (CWR)",
      party: "UDA",
    },
    {
      id: 301,
      name: "Wainaina, Antony Njoroge",
      constituency: "Kieni",
      party: "UDA",
    },
    {
      id: 302,
      name: "Wainaina, Michael Wambugu",
      constituency: "Othaya",
      party: "UDA",
    },
    {
      id: 303,
      name: "Waithaka, John Machua",
      constituency: "Kiambu",
      party: "UDA",
    },
    {
      id: 304,
      name: "Wamacukuru, James Githua Kamau",
      constituency: "Kabete",
      party: "UDA",
    },
    {
      id: 305,
      name: "Wamuchomba, Gathoni",
      constituency: "Githunguri",
      party: "UDA",
    },
    {
      id: 306,
      name: "John Njuguna",
      constituency: "Kiambaa",
      party: "UDA",
    },
    {
      id: 307,
      name: "Wanjira, Martha Wangari",
      constituency: "Gilgil",
      party: "UDA",
    },
    {
      id: 308,
      name: "Waqo, Naomi Jillo",
      constituency: "Marsabit (CWR)",
      party: "UDA",
    },
    {
      id: 309,
      name: "Waweru, John Kiarie",
      constituency: "Dagoretti South",
      party: "UDA",
    },
    {
      id: 310,
      name: "Yakub, Farah Salah",
      constituency: "Fafi",
      party: "UDA",
    },
    {
      id: 311,
      name: "Yegon, Brighton Leonard",
      constituency: "Konoin",
      party: "UDA",
    },
    {
      id: 312,
      name: "Yegon, Richard Kipkemoi",
      constituency: "Bomet East",
      party: "UDA",
    },
    {
      id: 313,
      name: "Abdullahi, Bashir Sheikh",
      constituency: "Mandera North",
      party: "UDM",
    },
    {
      id: 314,
      name: "Chiforomodo, Mangale Munga",
      constituency: "Lungalunga",
      party: "UDM",
    },
    {
      id: 315,
      name: "Haro, Abdul Ebrahim",
      constituency: "Mandera South",
      party: "UDM",
    },
    {
      id: 316,
      name: "Vacant",
      constituency: "Banissa",
    },
    {
      id: 317,
      name: "Harun, Suleka Hulbale",
      constituency: "Nominated",
      party: "UDM",
    },
    {
      id: 318,
      name: "Lekuton, Joseph",
      constituency: "Laisamis",
      party: "UDM",
    },
    {
      id: 319,
      name: "Sheikh, Umul Ker Kassim",
      constituency: "Mandera (CWR)",
      party: "UDM",
    },
    {
      id: 320,
      name: "Yussuf, Adan Haji",
      constituency: "Mandera West",
      party: "UDM",
    },
    {
      id: 321,
      name: "Onchoke Charles",
      constituency: "Bonchari",
      party: "UPA",
    },
    {
      id: 322,
      name: "Jaldesa, Guyo Waqo",
      constituency: "Moyale",
      party: "UPIA",
    },
    {
      id: 323,
      name: "Yakub, Adow Kuno",
      constituency: "Bura",
      party: "UPIA",
    },
    {
      id: 324,
      name: "Abdi, Khamis Chome",
      constituency: "Voi",
      party: "WDM",
    },
    {
      id: 325,
      name: "Aburi, Donya Dorice",
      constituency: "Kisii (CWR)",
      party: "WDM",
    },
    {
      id: 326,
      name: "Basil, Robert Ngui",
      constituency: "Yatta",
      party: "WDM",
    },
    {
      id: 327,
      name: "Bwire, John Okano",
      constituency: "Taveta",
      party: "WDM",
    },
    {
      id: 328,
      name: "Kamene, Joyce",
      constituency: "Machakos (CWR)",
      party: "WDM",
    },
    {
      id: 329,
      name: "Kasalu, Irene Muthoni",
      constituency: "Kitui (CWR)",
      party: "WDM",
    },
    {
      id: 330,
      name: "Kiamba, Suzanne Ndunge",
      constituency: "Makueni",
      party: "WDM",
    },
    {
      id: 331,
      name: "Kimilu, Joshua Kivinda",
      constituency: "Kaiti",
      party: "WDM",
    },
    {
      id: 332,
      name: "King’ola Patrick Makau",
      constituency: "Mavoko",
      party: "WDM",
    },
    {
      id: 333,
      name: "Maalim, Farah",
      constituency: "Dadaab",
      party: "WDM",
    },
    {
      id: 334,
      name: "Mawathe, Julius Musili",
      constituency: "Embakasi South",
      party: "WDM",
    },
    {
      id: 335,
      name: "Mbalu, Jessica Nduku Kiko",
      constituency: "Kibwezi East",
      party: "WDM",
    },
    {
      id: 336,
      name: "Mboni, David Mwalika",
      constituency: "Kitui Rural",
      party: "WDM",
    },
    {
      id: 337,
      name: "Mbui, Robert",
      constituency: "Kathiani",
      party: "WDM",
    },
    {
      id: 338,
      name: "Momanyi, Innocent Obiri",
      constituency: "Bomachoge Borabu",
      party: "WDM",
    },
    {
      id: 339,
      name: "Mule, Stephen Mutinda",
      constituency: "Matungulu",
      party: "WDM",
    },
    {
      id: 340,
      name: "Mulu, Makali Benson",
      constituency: "Kitui Central",
      party: "WDM",
    },
    {
      id: 341,
      name: "Mulyungi, Gideon Mutemi",
      constituency: "Mwingi Central",
      party: "WDM",
    },
    {
      id: 342,
      name: "Mumo, Rose Museo",
      constituency: "Makueni (CWR)",
      party: "WDM",
    },
    {
      id: 343,
      name: "Mwakuwona, Danson Mwashako",
      constituency: "Wundanyi",
      party: "WDM",
    },
    {
      id: 344,
      name: "Nguna, Charles Ngusya",
      constituency: "Mwingi West",
      party: "WDM",
    },
    {
      id: 345,
      name: "Nyenze, Edith Vethi",
      constituency: "Kitui West",
      party: "WDM",
    },
    {
      id: 346,
      name: "Nzambia, Thudeeus Kithua",
      constituency: "Kilome",
      party: "WDM",
    },
    {
      id: 347,
      name: "Nzengu, Paul Musyimi",
      constituency: "Mwingi North",
      party: "WDM",
    },
    {
      id: 348,
      name: "Nzioka, Erastus Kivasu",
      constituency: "Mbooni",
      party: "WDM",
    },
    {
      id: 349,
      name: "Twalib, Abubakar Ahmed",
      constituency: "Nominated",
      party: "WDM",
    },

];
