export const Members = [
  [
    {
      "No.": 1,
      NAME: "Adagala, Beatrice Kahai",
      CONSTITUENCY: "Vihiga (CWR)",
      PARTY: "ANC",
    },
    {
      "No.": 2,
      NAME: "Denar, Joseph Hamisi",
      CONSTITUENCY: "Nominated",
      PARTY: "ANC",
    },
    {
      "No.": 3,
      NAME: "Gimose, Charles Gumini",
      CONSTITUENCY: "Hamisi",
      PARTY: "ANC",
    },
    {
      "No.": 4,
      NAME: "IkanaM, Frederick Lusuli",
      CONSTITUENCY: "Shinyalu",
      PARTY: "ANC",
    },
    {
      "No.": 5,
      NAME: "Injendi, Moses Malulu",
      CONSTITUENCY: "Malava",
      PARTY: "ANC",
    },
    {
      "No.": 6,
      NAME: "Kagesi, Kivai Ernest Ogesi",
      CONSTITUENCY: "Vihiga",
      PARTY: "ANC",
    },
    {
      "No.": 7,
      NAME: "Omboko, Milemba Jeremiah",
      CONSTITUENCY: "Emuhaya",
      PARTY: "ANC",
    },
    {
      "No.": 8,
      NAME: "Tandaza, Kassim Sawa",
      CONSTITUENCY: "Matuga",
      PARTY: "ANC",
    },
    {
      "No.": 9,
      NAME: "Koech, Victor Kipngetich",
      CONSTITUENCY: "Chepalungu",
      PARTY: "CCM",
    },
    {
      "No.": 10,
      NAME: "Barasa, Patrick Simiyu",
      CONSTITUENCY: "Cherangany",
      PARTY: "DAP-K",
    },
    {
      "No.": 11,
      NAME: "Bisau, Maurice Kakai",
      CONSTITUENCY: "Kiminini",
      PARTY: "DAP-K",
    },
    {
      "No.": 12,
      NAME: "Oyugi, Dick Maungu",
      CONSTITUENCY: "Luanda",
      PARTY: "DAP-K",
    },
    {
      "No.": 13,
      NAME: "Salasya, Peter Kalerwa",
      CONSTITUENCY: "Mumias East",
      PARTY: "DAP-K",
    },
    {
      "No.": 14,
      NAME: "Wamboka, Nelson Jack Wamboka",
      CONSTITUENCY: "Bumula",
      PARTY: "DAP-K",
    },
    {
      "No.": 15,
      NAME: "Ruku, Geoffrey Kariuki Kiringa",
      CONSTITUENCY: "Mbeere North",
      PARTY: "DP",
    },
    {
      "No.": 16,
      NAME: "Kalasinga, Joseph Simiyu Wekesa Majimbo",
      CONSTITUENCY: "Kabuchai",
      PARTY: "FORD-K",
    },
    {
      "No.": 17,
      NAME: "Makali, John Okwisia",
      CONSTITUENCY: "Kanduyi",
      PARTY: "FORD-K",
    },
    {
      "No.": 18,
      NAME: "Murumba, John Chikati",
      CONSTITUENCY: "Tongaren",
      PARTY: "FORD-K",
    },
    {
      "No.": 19,
      NAME: "Wambilianga, Catherine Nanjala",
      CONSTITUENCY: "Busia (CWR)",
      PARTY: "FORD-K",
    },
    {
      "No.": 20,
      NAME: "Wanyonyi, Ferdinand Kevin",
      CONSTITUENCY: "Kwanza",
      PARTY: "FORD-K",
    },
    {
      "No.": 21,
      NAME: "Wanyonyi, Martin Pepela",
      CONSTITUENCY: "Webuye West",
      PARTY: "FORD-K",
    },
    {
      "No.": 22,
      NAME: "Muli, Fabian Kyule",
      CONSTITUENCY: "Kangundo",
      PARTY: "GDDP",
    },
    {
      "No.": 23,
      NAME: "Abdul, Rahim Dawood",
      CONSTITUENCY: "North Imenti",
      PARTY: "Independent",
    },
    {
      "No.": 24,
      NAME: "Ahmed, Shakeel Ahmed Shabbir",
      CONSTITUENCY: "Kisumu East",
      PARTY: "Independent",
    },
    {
      "No.": 25,
      NAME: "Caroline, Jeptoo Ng’elechei",
      CONSTITUENCY: "Elgeyo Marakwet (CWR)",
      PARTY: "Independent",
    },
    {
      "No.": 26,
      NAME: "Karauri, Ronald Kamwiko",
      CONSTITUENCY: "Kasarani",
      PARTY: "Independent",
    },
    {
      "No.": 27,
      NAME: "Kitilai, Ole Ntutu",
      CONSTITUENCY: "Narok South",
      PARTY: "Independent",
    },
    {
      "No.": 28,
      NAME: "Kururia, Elijah Njore Njoroge",
      CONSTITUENCY: "Gatundu North",
      PARTY: "Independent",
    },
    {
      "No.": 29,
      NAME: "Marubu, Monicah Muthoni",
      CONSTITUENCY: "Lamu (CWR)",
      PARTY: "Independent",
    },
    {
      "No.": 30,
      NAME: "Mohammed, Fatuma Zainabu",
      CONSTITUENCY: "Migori (CWR)",
      PARTY: "Independent",
    },
    {
      "No.": 31,
      NAME: "Mulanya, Geoffrey Ekesa",
      CONSTITUENCY: "Nambale",
      PARTY: "Independent",
    },
    {
      "No.": 32,
      NAME: "Mwalyo, Joshua Mbithi Mutua",
      CONSTITUENCY: "Masinga",
      PARTY: "Independent",
    },
    {
      "No.": 33,
      NAME: "Nebart, Bernard Muriuki",
      CONSTITUENCY: "Mbeere South",
      PARTY: "Independent",
    },
    {
      "No.": 34,
      NAME: "Toroitich, Timothy Kipchumba",
      CONSTITUENCY: "Marakwet West",
      PARTY: "Independent",
    },
    {
      "No.": 35,
      NAME: "Abdirahman, Mohamed Abdi",
      CONSTITUENCY: "Lafey",
      PARTY: "JP",
    },
    {
      "No.": 36,
      NAME: "Arama, Samuel",
      CONSTITUENCY: "Nakuru Town West",
      PARTY: "JP",
    },
    {
      "No.": 37,
      NAME: "Bonaya, Mumina Gollo",
      CONSTITUENCY: "Isiolo (CWR)",
      PARTY: "JP",
    },
    {
      "No.": 38,
      NAME: "Chege, Sabina Wanjiru",
      CONSTITUENCY: "Nominated",
      PARTY: "JP",
    },
    {
      "No.": 39,
      NAME: "Hassan, Abdi Yusuf",
      CONSTITUENCY: "Kamkunji",
      PARTY: "JP",
    },
    {
      "No.": 40,
      NAME: "Ithinji, Dr. Shadrack Mwiti",
      CONSTITUENCY: "South Imenti",
      PARTY: "JP",
    },
    {
      "No.": 41,
      NAME: "Karitho, Kiili Daniel",
      CONSTITUENCY: "Igembe Central",
      PARTY: "JP",
    },
    {
      "No.": 42,
      NAME: "Kiaraho, David Njuguna",
      CONSTITUENCY: "Ol Kalou",
      PARTY: "JP",
    },
    {
      "No.": 43,
      NAME: "Korere, Sarah Paulata",
      CONSTITUENCY: "Laikipia North",
      PARTY: "JP",
    },
    {
      "No.": 44,
      NAME: "Koyi, John Waluke",
      CONSTITUENCY: "Sirisia",
      PARTY: "JP",
    },
    {
      "No.": 45,
      NAME: "Kwenya, Thuku Zachary",
      CONSTITUENCY: "Kinangop",
      PARTY: "JP",
    },
    {
      "No.": 46,
      NAME: "Lomwa, Joseph Samal",
      CONSTITUENCY: "Isiolo North",
      PARTY: "JP",
    },
    {
      "No.": 47,
      NAME: "Maina, Mwago Amos",
      CONSTITUENCY: "Starehe",
      PARTY: "JP",
    },
    {
      "No.": 48,
      NAME: "Mogaka, Stephen M.",
      CONSTITUENCY: "West Mugirango",
      PARTY: "JP",
    },
    {
      "No.": 49,
      NAME: "Mohamed, Aden Daudi",
      CONSTITUENCY: "Wajir East",
      PARTY: "JP",
    },
    {
      "No.": 50,
      NAME: "Mongina, Jerusha Momanyi",
      CONSTITUENCY: "Nyamira (CWR)",
      PARTY: "JP",
    },
    {
      "No.": 51,
      NAME: "Mrembo, Irene Njoki",
      CONSTITUENCY: "Bahati",
      PARTY: "JP",
    },
    {
      "No.": 52,
      NAME: "Muiruri, Muthama Stanley",
      CONSTITUENCY: "Lamu West",
      PARTY: "JP",
    },
    {
      "No.": 53,
      NAME: "Mwenje, Mark Samuel Muriithi",
      CONSTITUENCY: "Embakasi West",
      PARTY: "JP",
    },
    {
      "No.": 54,
      NAME: "Ngikolong, Nicholas Ng’ikor Nixon",
      CONSTITUENCY: "Turkana East",
      PARTY: "JP",
    },
    {
      "No.": 55,
      NAME: "Nyamai, Rachael Kaki",
      CONSTITUENCY: "Kitui South",
      PARTY: "JP",
    },
    {
      "No.": 56,
      NAME: "Obo, Ruweida Mohamed",
      CONSTITUENCY: "Lamu East",
      PARTY: "JP",
    },
    {
      "No.": 57,
      NAME: "Pareiyo, Agnes Mantaine",
      CONSTITUENCY: "Narok North",
      PARTY: "JP",
    },
    {
      "No.": 58,
      NAME: "Shake, Peter Mbogho",
      CONSTITUENCY: "Mwatate",
      PARTY: "JP",
    },
    {
      "No.": 59,
      NAME: "Shurie, Abdi Omar",
      CONSTITUENCY: "Balambala",
      PARTY: "JP",
    },
    {
      "No.": 60,
      NAME: "Siyad, Amina Udgoon",
      CONSTITUENCY: "Garissa (CWR)",
      PARTY: "JP",
    },
    {
      "No.": 61,
      NAME: "Tubi, Bidu Mohamed",
      CONSTITUENCY: "Isiolo South",
      PARTY: "JP",
    },
    {
      "No.": 62,
      NAME: "Wehliye, Adan Keynan",
      CONSTITUENCY: "Eldas",
      PARTY: "JP`",
    },
    {
      "No.": 63,
      NAME: "Abdullahi, Amina Dika",
      CONSTITUENCY: "Tana River (CWR)",
      PARTY: "KANU",
    },
    {
      "No.": 64,
      NAME: "Guyo, Adhe Wario",
      CONSTITUENCY: "North Horr",
      PARTY: "KANU",
    },
    {
      "No.": 65,
      NAME: "Kassait, William Kamket",
      CONSTITUENCY: "Tiaty",
      PARTY: "KANU",
    },
    {
      "No.": 66,
      NAME: "Lentoijoni, Jackson Lekumontare",
      CONSTITUENCY: "Samburu East",
      PARTY: "KANU",
    },
    {
      "No.": 67,
      NAME: "Lesuuda, Josephine Naisula",
      CONSTITUENCY: "Samburu West",
      PARTY: "KANU",
    },
    {
      "No.": 68,
      NAME: "Sunkuli, Julius Lekakeny Ole",
      CONSTITUENCY: "Kilgoris",
      PARTY: "KANU",
    },
    {
      "No.": 69,
      NAME: "Kasiwai, Rael Chepkemoi",
      CONSTITUENCY: "West Pokot (CWR)",
      PARTY: "KUP",
    },
    {
      "No.": 70,
      NAME: "Pkosing, David Losiakou",
      CONSTITUENCY: "Pokot South",
      PARTY: "KUP",
    },
    {
      "No.": 71,
      NAME: "Titus, Lotee",
      CONSTITUENCY: "Kacheliba",
      PARTY: "KUP",
    },
    {
      "No.": 72,
      NAME: "Mule, Caleb Mutiso",
      CONSTITUENCY: "Machakos Town",
      PARTY: "MCCP",
    },
    {
      "No.": 73,
      NAME: "Mutuse, Eckomas Mwengi",
      CONSTITUENCY: "Kibwezi West",
      PARTY: "MCCP",
    },
    {
      "No.": 74,
      NAME: "Ochieng, David Ouma",
      CONSTITUENCY: "Ugenya",
      PARTY: "MDG",
    },
    {
      "No.": 75,
      NAME: "Abdi, Abdi Ali",
      CONSTITUENCY: "Ijara",
      PARTY: "NAP-K",
    },
    {
      "No.": 76,
      NAME: "Aburi, Lawrence Mpuru",
      CONSTITUENCY: "Tigania East",
      PARTY: "NOPEU",
    },
    {
      "No.": 77,
      NAME: "Abdirahman, Husseinweytan Mohamed",
      CONSTITUENCY: "Mandera East",
      PARTY: "ODM",
    },
    {
      "No.": 78,
      NAME: "Abuor, Paul",
      CONSTITUENCY: "Rongo",
      PARTY: "ODM",
    },
    {
      "No.": 79,
      NAME: "Adow, Mohamed Aden",
      CONSTITUENCY: "Wajir South",
      PARTY: "ODM",
    },
    {
      "No.": 80,
      NAME: "Amollo, Paul Otiende",
      CONSTITUENCY: "Rarieda",
      PARTY: "ODM",
    },
    {
      "No.": 81,
      NAME: "Samuel Onunga",
      CONSTITUENCY: "Alego Usonga",
      PARTY: "ODM",
    },
    {
      "No.": 82,
      NAME: "Bady, Bady Twalib",
      CONSTITUENCY: "Jomvu",
      PARTY: "ODM",
    },
    {
      "No.": 83,
      NAME: "Barongo, Nolfason Obadiah",
      CONSTITUENCY: "Bomachoge Borabu",
      PARTY: "ODM",
    },
    {
      "No.": 84,
      NAME: "Bedzimba, Rashid Juma",
      CONSTITUENCY: "Kisauni",
      PARTY: "ODM",
    },
    {
      "No.": 85,
      NAME: "Busia, Ruth Adhiambo Odinga",
      CONSTITUENCY: "Kisumu (CWR)",
      PARTY: "ODM",
    },
    {
      "No.": 86,
      NAME: "Buyu, Rozaah Akinyi",
      CONSTITUENCY: "Kisumu West",
      PARTY: "ODM",
    },
    {
      "No.": 87,
      NAME: "Chimba, Zamzam Mohamed",
      CONSTITUENCY: "Mombasa (CWR)",
      PARTY: "ODM",
    },
    {
      "No.": 88,
      NAME: "Elachi, Beatrice Kadeveresia",
      CONSTITUENCY: "Dagoretti North",
      PARTY: "ODM",
    },
    {
      "No.": 89,
      NAME: "Farah, Yussuf Mohamed",
      CONSTITUENCY: "Wajir West",
      PARTY: "ODM",
    },
    {
      "No.": 90,
      NAME: "Francis, Kajwang’ Tom Joseph",
      CONSTITUENCY: "Ruaraka",
      PARTY: "ODM",
    },
    {
      "No.": 91,
      NAME: "Gisairo, Clive Ombane",
      CONSTITUENCY: "Kitutu Masaba",
      PARTY: "ODM",
    },
    {
      "No.": 92,
      NAME: "Gogo, Lilian Achieng",
      CONSTITUENCY: "Rangwe",
      PARTY: "ODM",
    },
    {
      "No.": 93,
      NAME: "Guyo, Ali Wario",
      CONSTITUENCY: "Garsen",
      PARTY: "ODM",
    },
    {
      "No.": 94,
      NAME: "Hamisi, Kakuta Maimai",
      CONSTITUENCY: "Kajiado East",
      PARTY: "ODM",
    },
    {
      "No.": 95,
      NAME: "Hiribae, Said Buya",
      CONSTITUENCY: "Galole",
      PARTY: "ODM",
    },
    {
      "No.": 96,
      NAME: "Jehow, Fatuma Abdi",
      CONSTITUENCY: "Wajir (CWR)",
      PARTY: "ODM",
    },
    {
      "No.": 97,
      NAME: "Kaluma, George Peter Opondo",
      CONSTITUENCY: "Homa Bay Town",
      PARTY: "ODM",
    },
    {
      "No.": 98,
      NAME: "Kanchory, Elijah Memusi",
      CONSTITUENCY: "Kajiado Central",
      PARTY: "ODM",
    },
    {
      "No.": 99,
      NAME: "Katana, Paul Kahindi",
      CONSTITUENCY: "Kaloleni",
      PARTY: "ODM",
    },
    {
      "No.": 100,
      NAME: "Khodhe, Phelix Odiwuor",
      CONSTITUENCY: "Langata",
      PARTY: "ODM",
    },
    {
      "No.": 101,
      NAME: "Kibagendi, Antoney",
      CONSTITUENCY: "Kitutu Chache South",
      PARTY: "ODM",
    },
    {
      "No.": 102,
      NAME: "Kiti, Richard Ken Chonga",
      CONSTITUENCY: "Kilifi South",
      PARTY: "ODM",
    },
    {
      "No.": 103,
      NAME: "Kombe, Harrison Garama",
      CONSTITUENCY: "Magarini",
      PARTY: "ODM",
    },
    {
      "No.": 104,
      NAME: "Luyai, Caleb Amisi",
      CONSTITUENCY: "Saboti",
      PARTY: "ODM",
    },
    {
      "No.": 105,
      NAME: "Machele, Mohamed Soud",
      CONSTITUENCY: "Mvita",
      PARTY: "ODM",
    },
    {
      "No.": 106,
      NAME: "Manduku, Daniel Ogwoka",
      CONSTITUENCY: "Nyaribari Masaba",
      PARTY: "ODM",
    },
    {
      "No.": 107,
      NAME: "Masara, Peter Francis",
      CONSTITUENCY: "Suna West",
      PARTY: "ODM",
    },
    {
      "No.": 108,
      NAME: "Masito, Fatuma Hamisi",
      CONSTITUENCY: "Kwale (CWR)",
      PARTY: "ODM",
    },
    {
      "No.": 109,
      NAME: "Mayaka, Irene Nyakerario",
      CONSTITUENCY: "Nominated",
      PARTY: "ODM",
    },
    {
      "No.": 110,
      NAME: "Mboko, Mishi Juma Khamisi",
      CONSTITUENCY: "Likoni",
      PARTY: "ODM",
    },
    {
      "No.": 111,
      NAME: "Mohamed, Abdikadir Hussein",
      CONSTITUENCY: "Lagdera",
      PARTY: "ODM",
    },
    {
      "No.": 112,
      NAME: "Mohamed, Junet Sheikh Nuh",
      CONSTITUENCY: "Suna East",
      PARTY: "ODM",
    },
    {
      "No.": 113,
      NAME: "Mohamed, Umulkher Harun",
      CONSTITUENCY: "Nominated",
      PARTY: "ODM",
    },
    {
      "No.": 114,
      NAME: "Mugabe, Innocent Maino",
      CONSTITUENCY: "Likuyani",
      PARTY: "ODM",
    },
    {
      "No.": 115,
      NAME: "Muhanda, Elsie Busihile",
      CONSTITUENCY: "Kakamega (CWR)",
      PARTY: "ODM",
    },
    {
      "No.": 116,
      NAME: "Mukhwana, Titus Khamala",
      CONSTITUENCY: "Lurambi",
      PARTY: "ODM",
    },
    {
      "No.": 117,
      NAME: "Mwale, Nicholas S. Tindi",
      CONSTITUENCY: "Butere",
      PARTY: "ODM",
    },
    {
      "No.": 118,
      NAME: "Mwanyanje, Gertrude Mbeyu",
      CONSTITUENCY: "Kilifi (CWR)",
      PARTY: "ODM",
    },
    {
      "No.": 119,
      NAME: "Mnyazi, Amina Laura",
      CONSTITUENCY: "Malindi",
      PARTY: "ODM",
    },
    {
      "No.": 120,
      NAME: "Nabii, Nabwera Daraja",
      CONSTITUENCY: "Lugari",
      PARTY: "ODM",
    },
    {
      "No.": 121,
      NAME: "Nabulindo, Peter Oscar",
      CONSTITUENCY: "Matungu",
      PARTY: "ODM",
    },
    {
      "No.": 122,
      NAME: "Naibun, Paul Ekwom",
      CONSTITUENCY: "Turkana North",
      PARTY: "ODM",
    },
    {
      "No.": 123,
      NAME: "Naicca, Johnson Manya",
      CONSTITUENCY: "Mumias West",
      PARTY: "ODM",
    },
    {
      "No.": 124,
      NAME: "Namoit, John Ariko",
      CONSTITUENCY: "Turkana South",
      PARTY: "ODM",
    },
    {
      "No.": 125,
      NAME: "Ng’ongo, John Mbadi",
      CONSTITUENCY: "Nominated",
      PARTY: "ODM",
    },
    {
      "No.": 126,
      NAME: "Nyamita, Mark Ogolla",
      CONSTITUENCY: "Uriri",
      PARTY: "ODM",
    },
    {
      "No.": 127,
      NAME: "Nyikal, James Wambura",
      CONSTITUENCY: "Seme",
      PARTY: "ODM",
    },
    {
      "No.": 128,
      NAME: "Obara, Eve Akinyi",
      CONSTITUENCY: "Kabondo Kasipul",
      PARTY: "ODM",
    },
    {
      "No.": 129,
      NAME: "Odanga, Geoffrey Makokha",
      CONSTITUENCY: "Matayos",
      PARTY: "ODM",
    },
    {
      "No.": 130,
      NAME: "Odege, Tom Mboya",
      CONSTITUENCY: "Nyatike",
      PARTY: "ODM",
    },
    {
      "No.": 131,
      NAME: "Odhiambo, Elisha Ochieng",
      CONSTITUENCY: "Gem",
      PARTY: "ODM",
    },
    {
      "No.": 132,
      NAME: "Odhiambo, Millie Grace Akoth",
      CONSTITUENCY: "Suba North",
      PARTY: "ODM",
    },
    {
      "No.": 133,
      NAME: "Odoyo, Okello Jared",
      CONSTITUENCY: "Nyando",
      PARTY: "ODM",
    },
    {
      "No.": 134,
      NAME: "Oduor, Christine Ombaka",
      CONSTITUENCY: "Siaya (CWR)",
      PARTY: "ODM",
    },
    {
      "No.": 135,
      NAME: "Ogolla, Gideon Ochanda",
      CONSTITUENCY: "Bondo",
      PARTY: "ODM",
    },
    {
      "No.": 136,
      NAME: "Oku, Edward Kaunya",
      CONSTITUENCY: "Teso North",
      PARTY: "ODM",
    },
    {
      "No.": 137,
      NAME: "Okuome, Andrew Adipo",
      CONSTITUENCY: "Karachuonyo",
      PARTY: "ODM",
    },
    {
      "No.": 138,
      NAME: "Oluoch, Anthony Tom",
      CONSTITUENCY: "Mathare",
      PARTY: "ODM",
    },
    {
      "No.": 139,
      NAME: "Omanyo, Catherine Nakhabi",
      CONSTITUENCY: "Busia (CWR)",
      PARTY: "ODM",
    },
    {
      "No.": 140,
      NAME: "Omondi, Caroli",
      CONSTITUENCY: "Suba South",
      PARTY: "ODM",
    },
    {
      "No.": 141,
      NAME: "Omwera, George Aladwa",
      CONSTITUENCY: "Makadara",
      PARTY: "ODM",
    },
    {
      "No.": 142,
      NAME: "Ongili, Babu Owino Paul",
      CONSTITUENCY: "Embakasi East",
      PARTY: "ODM",
    },
    {
      "No.": 143,
      NAME: "Orero, Peter Ochieng",
      CONSTITUENCY: "Kibra",
      PARTY: "ODM",
    },
    {
      "No.": 144,
      NAME: "Oron, Joshua Odongo",
      CONSTITUENCY: "Kisumu Central",
      PARTY: "ODM",
    },
    {
      "No.": 145,
      NAME: "Osero, Patrick Kibagendi",
      CONSTITUENCY: "Borabu",
      PARTY: "ODM",
    },
    {
      "No.": 146,
      NAME: "Osogo, Bensuda Joyce Atieno",
      CONSTITUENCY: "Homa Bay (CWR)",
      PARTY: "ODM",
    },
    {
      "No.": 147,
      NAME: "Oundo, Wilberforce Ojiambo",
      CONSTITUENCY: "Funyula",
      PARTY: "ODM",
    },
    {
      "No.": 148,
      NAME: "Owino, John Walter",
      CONSTITUENCY: "Awendo",
      PARTY: "ODM",
    },
    {
      "No.": 149,
      NAME: "Owino, Martin Peters",
      CONSTITUENCY: "Ndhiwa",
      PARTY: "ODM",
    },
    {
      "No.": 150,
      NAME: "Owuor, Joshua Aduma",
      CONSTITUENCY: "Nyakach",
      PARTY: "ODM",
    },
    {
      "No.": 151,
      NAME: "Oyoo, James Onyango",
      CONSTITUENCY: "Muhoroni",
      PARTY: "ODM",
    },
    {
      "No.": 152,
      NAME: "Oyula, Joseph H. Maero",
      CONSTITUENCY: "Butula",
      PARTY: "ODM",
    },
    {
      "No.": 153,
      NAME: "Passaris, Esther Muthomi",
      CONSTITUENCY: "Nairobi City (CWR)",
      PARTY: "ODM",
    },
    {
      "No.": 154,
      NAME: "Sakimba, Parashina Samuel",
      CONSTITUENCY: "Kajiado South",
      PARTY: "ODM",
    },
    {
      "No.": 155,
      NAME: "Shimbwa, Omar Mwinyi",
      CONSTITUENCY: "Changamwe",
      PARTY: "ODM",
    },
    {
      "No.": 156,
      NAME: "Shinali, Bernard Masaka",
      CONSTITUENCY: "Ikolomani",
      PARTY: "ODM",
    },
    {
      "No.": 157,
      NAME: "Wandayi, James Opiyo",
      CONSTITUENCY: "Ugunja",
      PARTY: "ODM",
    },
    {
      "No.": 158,
      NAME: "Wangaya, Christopher Aseka",
      CONSTITUENCY: "Khwisero",
      PARTY: "ODM",
    },
    {
      "No.": 159,
      NAME: "Wangwe, Emmanuel",
      CONSTITUENCY: "Navakholo",
      PARTY: "ODM",
    },
    {
      "No.": 160,
      NAME: "Wanjala, Raphael Sauti Bitta",
      CONSTITUENCY: "Budalangi",
      PARTY: "ODM",
    },
    {
      "No.": 161,
      NAME: "Were, Charles Ong’ondo",
      CONSTITUENCY: "Kasipul",
      PARTY: "ODM",
    },
    {
      "No.": 162,
      NAME: "Wetangula, Timothy Wanyonyi",
      CONSTITUENCY: "Westlands",
      PARTY: "ODM",
    },
    {
      "No.": 163,
      NAME: "Mupe, Anthony Kenga",
      CONSTITUENCY: "Rabai",
      PARTY: "PAA",
    },
    {
      "No.": 164,
      NAME: "Rai, Samuel Gonzi",
      CONSTITUENCY: "Kinango",
      PARTY: "PAA",
    },
    {
      "No.": 165,
      NAME: "Tungule, Charo Kenneth Kazungu",
      CONSTITUENCY: "Ganze",
      PARTY: "PAA",
    },
    {
      "No.": 166,
      NAME: "Kiunjuri, Festus Mwangi",
      CONSTITUENCY: "Laikipia East",
      PARTY: "TSP",
    },
    {
      "No.": 167,
      NAME: "Nduyo, Susan Ngugi",
      CONSTITUENCY: "Tharaka-Nithi(CWR)",
      PARTY: "TSP",
    },
    {
      "No.": 168,
      NAME: "Akuja, Protus Ewesit",
      CONSTITUENCY: "Loima",
      PARTY: "UDA",
    },
    {
      "No.": 169,
      NAME: "Alfah, Miruka Ondieki",
      CONSTITUENCY: "Bomachoge Chache",
      PARTY: "UDA",
    },
    {
      "No.": 170,
      NAME: "Ali, Abdisirat Khalif",
      CONSTITUENCY: "Nominated",
      PARTY: "UDA",
    },
    {
      "No.": 171,
      NAME: "Bader, Salim Feisal",
      CONSTITUENCY: "Msambweni",
      PARTY: "UDA",
    },
    {
      "No.": 172,
      NAME: "Barre, Hussein Abdi",
      CONSTITUENCY: "Tarbaj",
      PARTY: "UDA",
    },
    {
      "No.": 173,
      NAME: "Barrow, Dekow Mohamed",
      CONSTITUENCY: "Garissa Township",
      PARTY: "UDA",
    },
    {
      "No.": 174,
      NAME: "Bartoo, Phylis Jepkemoi",
      CONSTITUENCY: "Moiben",
      PARTY: "UDA",
    },
    {
      "No.": 175,
      NAME: "Baya, Owen Yaa",
      CONSTITUENCY: "Kilifi North",
      PARTY: "UDA",
    },
    {
      "No.": 176,
      NAME: "Biego, Paul Kibichy",
      CONSTITUENCY: "Chesumei",
      PARTY: "UDA",
    },
    {
      "No.": 177,
      NAME: "Bowen, David Kangogo",
      CONSTITUENCY: "Marakwet East",
      PARTY: "UDA",
    },
    {
      "No.": 178,
      NAME: "Chebor, Paul Kibet",
      CONSTITUENCY: "Rongai",
      PARTY: "UDA",
    },
    {
      "No.": 179,
      NAME: "Chege, John Kiragu",
      CONSTITUENCY: "Limuru",
      PARTY: "UDA",
    },
    {
      "No.": 180,
      NAME: "Chelule, Liza Chepkorir",
      CONSTITUENCY: "Nakuru (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 181,
      NAME: "Chepkonga, Kiprono Samwel",
      CONSTITUENCY: "Ainabkoi",
      PARTY: "UDA",
    },
    {
      "No.": 182,
      NAME: "Chepkorir, Linet",
      CONSTITUENCY: "Bomet (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 183,
      NAME: "Chepkwony, Charity Kathambi",
      CONSTITUENCY: "Njoro",
      PARTY: "UDA",
    },
    {
      "No.": 184,
      NAME: "Cherorot, Joseph Kimutai",
      CONSTITUENCY: "Kipkelion East",
      PARTY: "UDA",
    },
    {
      "No.": 185,
      NAME: "Chesebe, Fred Kapondi",
      CONSTITUENCY: "Mt. Elgon",
      PARTY: "UDA",
    },
    {
      "No.": 186,
      NAME: "Chumel, Samwel Moroto",
      CONSTITUENCY: "Kapenguria",
      PARTY: "UDA",
    },
    {
      "No.": 187,
      NAME: "Double N, Pamela Njoki Njeru",
      CONSTITUENCY: "Embu (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 188,
      NAME: "Emathe, Joseph Namuar",
      CONSTITUENCY: "Turkana Central",
      PARTY: "UDA",
    },
    {
      "No.": 189,
      NAME: "Gachagua, George N.",
      CONSTITUENCY: "Ndaragwa",
      PARTY: "UDA",
    },
    {
      "No.": 190,
      NAME: "Gachobe, Samuel Kinuthia",
      CONSTITUENCY: "Subukia",
      PARTY: "UDA",
    },
    {
      "No.": 191,
      NAME: "Gakuya, James Mwangi",
      CONSTITUENCY: "Embakasi North",
      PARTY: "UDA",
    },
    {
      "No.": 192,
      NAME: "Gathiru, Mejjadonk Benjamin",
      CONSTITUENCY: "Embakasi Central",
      PARTY: "UDA",
    },
    {
      "No.": 193,
      NAME: "Gichohi, Kaguchia John Philip",
      CONSTITUENCY: "Mukurweini",
      PARTY: "UDA",
    },
    {
      "No.": 194,
      NAME: "Gichuki, Edwin Mugo",
      CONSTITUENCY: "Mathioya",
      PARTY: "UDA",
    },
    {
      "No.": 195,
      NAME: "Gikaria, David",
      CONSTITUENCY: "Nakuru Town East",
      PARTY: "UDA",
    },
    {
      "No.": 196,
      NAME: "Gitari, Joseph Gachoki",
      CONSTITUENCY: "Kirinyaga Central",
      PARTY: "UDA",
    },
    {
      "No.": 197,
      NAME: "Gitau, Faith Wairimu",
      CONSTITUENCY: "Nyandarua (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 198,
      NAME: "Githinji, Robert Gichimu",
      CONSTITUENCY: "Gichugu",
      PARTY: "UDA",
    },
    {
      "No.": 199,
      NAME: "GK, George Macharia Kariuki",
      CONSTITUENCY: "Ndia",
      PARTY: "UDA",
    },
    {
      "No.": 200,
      NAME: "Ichung’wah, Anthony Kimani",
      CONSTITUENCY: "Kikuyu",
      PARTY: "UDA",
    },
    {
      "No.": 201,
      NAME: "Ikiara, Dorothy Muthoni",
      CONSTITUENCY: "Nominated",
      PARTY: "UDA",
    },
    {
      "No.": 202,
      NAME: "Iraya, Joseph Wainaina",
      CONSTITUENCY: "Nominated",
      PARTY: "UDA",
    },
    {
      "No.": 203,
      NAME: "Jhanda Zaheer",
      CONSTITUENCY: "Nyaribari Chache",
      PARTY: "UDA",
    },
    {
      "No.": 204,
      NAME: "Kagiri, Jane Wangechi",
      CONSTITUENCY: "Laikipia (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 205,
      NAME: "Kagombe, Gabriel Gathuka",
      CONSTITUENCY: "Gatundu South",
      PARTY: "UDA",
    },
    {
      "No.": 206,
      NAME: "Kahangara, Joseph Mburu",
      CONSTITUENCY: "Lari",
      PARTY: "UDA",
    },
    {
      "No.": 207,
      NAME: "Kahugu, Eric Meangi",
      CONSTITUENCY: "Mathira",
      PARTY: "UDA",
    },
    {
      "No.": 208,
      NAME: "Kailema, Elizabeth Karambu",
      CONSTITUENCY: "Meru (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 209,
      NAME: "Kamuren, Charles",
      CONSTITUENCY: "Baringo South",
      PARTY: "UDA",
    },
    {
      "No.": 210,
      NAME: "Kandie, Joshua Chepyegon",
      CONSTITUENCY: "Baringo Central",
      PARTY: "UDA",
    },
    {
      "No.": 211,
      NAME: "Karani, Stephen Wachira",
      CONSTITUENCY: "Laikipia West",
      PARTY: "UDA",
    },
    {
      "No.": 212,
      NAME: "Karemba, Eric Muchangi Njiru",
      CONSTITUENCY: "Runyenjes",
      PARTY: "UDA",
    },
    {
      "No.": 213,
      NAME: "Kemei, Beatrice Chepng’eno",
      CONSTITUENCY: "Kericho (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 214,
      NAME: "Kemei, Justice Kipsang",
      CONSTITUENCY: "Sigowet/Soin",
      PARTY: "UDA",
    },
    {
      "No.": 215,
      NAME: "Kemero, Maisori Marwa Kitayama",
      CONSTITUENCY: "Kuria East",
      PARTY: "UDA",
    },
    {
      "No.": 216,
      NAME: "Kihara, Jayne Wanjiru Njeru",
      CONSTITUENCY: "Naivasha",
      PARTY: "UDA",
    },
    {
      "No.": 217,
      NAME: "Kihungi, Peter Irungu",
      CONSTITUENCY: "Kangema",
      PARTY: "UDA",
    },
    {
      "No.": 218,
      NAME: "Kilel, Richard Cheruiyot",
      CONSTITUENCY: "Bomet Central",
      PARTY: "UDA",
    },
    {
      "No.": 219,
      NAME: "Kimani, Francis Kuria",
      CONSTITUENCY: "Molo",
      PARTY: "UDA",
    },
    {
      "No.": 220,
      NAME: "Kingara, Simon Ng’ang’a",
      CONSTITUENCY: "Ruiru",
      PARTY: "UDA",
    },
    {
      "No.": 221,
      NAME: "Kipbiwot, Julius Melly",
      CONSTITUENCY: "Tinderet",
      PARTY: "UDA",
    },
    {
      "No.": 222,
      NAME: "Kipgnor, Reuben Kiborek",
      CONSTITUENCY: "Mogotio",
      PARTY: "UDA",
    },
    {
      "No.": 223,
      NAME: "Kipkoech, Gideon Kimaiyo",
      CONSTITUENCY: "Keiyo South",
      PARTY: "UDA",
    },
    {
      "No.": 224,
      NAME: "Kipkoros, Joseph Makilap",
      CONSTITUENCY: "Baringo North",
      PARTY: "UDA",
    },
    {
      "No.": 225,
      NAME: "Kiplagat, David",
      CONSTITUENCY: "Soy",
      PARTY: "UDA",
    },
    {
      "No.": 226,
      NAME: "Kiprono, Mutai Alfred",
      CONSTITUENCY: "Kuresoi North",
      PARTY: "UDA",
    },
    {
      "No.": 227,
      NAME: "Kipyegon, Johana Ng’eno",
      CONSTITUENCY: "Emurua Dikirr",
      PARTY: "UDA",
    },
    {
      "No.": 228,
      NAME: "Kirima, Moses Nguchine",
      CONSTITUENCY: "Central Imenti",
      PARTY: "UDA",
    },
    {
      "No.": 229,
      NAME: "Kirwa, Abraham Kipsang",
      CONSTITUENCY: "Mosop",
      PARTY: "UDA",
    },
    {
      "No.": 230,
      NAME: "Kitany, Marianne Jebet",
      CONSTITUENCY: "Aldai",
      PARTY: "UDA",
    },
    {
      "No.": 231,
      NAME: "Kitur, Bernard Kibor",
      CONSTITUENCY: "Nandi Hills",
      PARTY: "UDA",
    },
    {
      "No.": 232,
      NAME: "Koech, Nelson",
      CONSTITUENCY: "Belgut",
      PARTY: "UDA",
    },
    {
      "No.": 233,
      NAME: "Komingoi, Kibet Kirui",
      CONSTITUENCY: "Bureti",
      PARTY: "UDA",
    },
    {
      "No.": 234,
      NAME: "Korir, Adams Kipsanai",
      CONSTITUENCY: "Keiyo North",
      PARTY: "UDA",
    },
    {
      "No.": 235,
      NAME: "Kosgei, Hilary Kiplangat",
      CONSTITUENCY: "Kipkelion West",
      PARTY: "UDA",
    },
    {
      "No.": 236,
      NAME: "Kosgei, Jackson Kipkemoi",
      CONSTITUENCY: "Nominated",
      PARTY: "UDA",
    },
    {
      "No.": 237,
      NAME: "Langat, Benjamin Kipkirui",
      CONSTITUENCY: "Ainamoi",
      PARTY: "UDA",
    },
    {
      "No.": 238,
      NAME: "Lelmengit, Josses Kiptoo Kosgey",
      CONSTITUENCY: "Emgwen",
      PARTY: "UDA",
    },
    {
      "No.": 239,
      NAME: "Lemanken, Aramat",
      CONSTITUENCY: "Narok East",
      PARTY: "UDA",
    },
    {
      "No.": 240,
      NAME: "Lenguris, Pauline",
      CONSTITUENCY: "Samburu (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 241,
      NAME: "Letipila, Dominic Eli",
      CONSTITUENCY: "Samburu North",
      PARTY: "UDA",
    },
    {
      "No.": 242,
      NAME: "Lochakapong, Peter",
      CONSTITUENCY: "Sigor",
      PARTY: "UDA",
    },
    {
      "No.": 243,
      NAME: "Logova, Sloya Clement",
      CONSTITUENCY: "Sabatia",
      PARTY: "UDA",
    },
    {
      "No.": 244,
      NAME: "M’Anaiba, Julius Taitumu",
      CONSTITUENCY: "Igembe North",
      PARTY: "UDA",
    },
    {
      "No.": 245,
      NAME: "Maina, Betty Njeri",
      CONSTITUENCY: "Murang’a (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 246,
      NAME: "Maina, Jane Njeri",
      CONSTITUENCY: "Kirinyaga (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 247,
      NAME: "Maingi, Mary",
      CONSTITUENCY: "Mwea",
      PARTY: "UDA",
    },
    {
      "No.": 248,
      NAME: "Mathenge, Duncan Maina",
      CONSTITUENCY: "Nyeri Town",
      PARTY: "UDA",
    },
    {
      "No.": 249,
      NAME: "Mbai, Nimrod Mbithuka",
      CONSTITUENCY: "Kitui East",
      PARTY: "UDA",
    },
    {
      "No.": 250,
      NAME: "Mbiuki, Japhet Miriti Kareke",
      CONSTITUENCY: "Maara",
      PARTY: "UDA",
    },
    {
      "No.": 251,
      NAME: "Mizighi, Lydia Haika Mnene",
      CONSTITUENCY: "Taita Taveta (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 252,
      NAME: "Mohamed, Mohamed Ali",
      CONSTITUENCY: "Nyali",
      PARTY: "UDA",
    },
    {
      "No.": 253,
      NAME: "Mokaya, Nyakundi Japheth",
      CONSTITUENCY: "Kitutu Chache North",
      PARTY: "UDA",
    },
    {
      "No.": 254,
      NAME: "Muchira, Michael Mwangi",
      CONSTITUENCY: "Ol Jorok",
      PARTY: "UDA",
    },
    {
      "No.": 255,
      NAME: "Muge, Cynthia Jepkosgei",
      CONSTITUENCY: "Nandi (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 256,
      NAME: "Muhia, Wanjiku",
      CONSTITUENCY: "Kipipiri",
      PARTY: "UDA",
    },
    {
      "No.": 257,
      NAME: "Mukunji, John Gitonga Mwaniki",
      CONSTITUENCY: "Manyatta",
      PARTY: "UDA",
    },
    {
      "No.": 258,
      NAME: "Munyoro, Joseph Kamau",
      CONSTITUENCY: "Kigumo",
      PARTY: "UDA",
    },
    {
      "No.": 259,
      NAME: "Muratha, Anne Wanjiku Mugo",
      CONSTITUENCY: "Kiambu (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 260,
      NAME: "Muriu, Wakili Edward",
      CONSTITUENCY: "Gatanga",
      PARTY: "UDA",
    },
    {
      "No.": 261,
      NAME: "Murugara, George Gitonga",
      CONSTITUENCY: "Tharaka",
      PARTY: "UDA",
    },
    {
      "No.": 262,
      NAME: "Murwithania, Rindikiri Mugambi",
      CONSTITUENCY: "Buuri",
      PARTY: "UDA",
    },
    {
      "No.": 263,
      NAME: "Musau, Vincent Musyoka",
      CONSTITUENCY: "Mwala",
      PARTY: "UDA",
    },
    {
      "No.": 264,
      NAME: "Mutua, Didmus Wekesa Barasa",
      CONSTITUENCY: "Kimilili",
      PARTY: "UDA",
    },
    {
      "No.": 265,
      NAME: "Mutunga, John Kanyuithia",
      CONSTITUENCY: "Tigania West",
      PARTY: "UDA",
    },
    {
      "No.": 266,
      NAME: "Mwafrika, Augustine Kamande",
      CONSTITUENCY: "Royasambu",
      PARTY: "UDA",
    },
    {
      "No.": 267,
      NAME: "Mwangi, Geoffrey Wandeto",
      CONSTITUENCY: "Tetu",
      PARTY: "UDA",
    },
    {
      "No.": 268,
      NAME: "Mwangi, Teresia Wanjiru",
      CONSTITUENCY: "Nominated",
      PARTY: "UDA",
    },
    {
      "No.": 269,
      NAME: "Mwiring, John Paul",
      CONSTITUENCY: "Igembe South",
      PARTY: "UDA",
    },
    {
      "No.": 270,
      NAME: "Nanok, Daniel Epuyo",
      CONSTITUENCY: "Turkana West",
      PARTY: "UDA",
    },
    {
      "No.": 271,
      NAME: "Ndung’u George Koimburi",
      CONSTITUENCY: "Juja",
      PARTY: "UDA",
    },
    {
      "No.": 272,
      NAME: "Ng’ang’a Alice Wambui",
      CONSTITUENCY: "Thika Town",
      PARTY: "UDA",
    },
    {
      "No.": 273,
      NAME: "Ngitit, Cecilia Asinyen",
      CONSTITUENCY: "Turkana (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 274,
      NAME: "Nguro, Onesmus Ngogoyo",
      CONSTITUENCY: "Kajiado North",
      PARTY: "UDA",
    },
    {
      "No.": 275,
      NAME: "Njoroge, Mary Wamaua Waithira",
      CONSTITUENCY: "Maragwa",
      PARTY: "UDA",
    },
    {
      "No.": 276,
      NAME: "Njuguna, Chege",
      CONSTITUENCY: "Kandara",
      PARTY: "UDA",
    },
    {
      "No.": 277,
      NAME: "Ntwiga, Patrick Munene",
      CONSTITUENCY: "Chuka/Igambang’ombe",
      PARTY: "UDA",
    },
    {
      "No.": 278,
      NAME: "Nyamoko, Joash Nyamache",
      CONSTITUENCY: "North Mugirango",
      PARTY: "UDA",
    },
    {
      "No.": 279,
      NAME: "Nyoro, Samson Ndindi",
      CONSTITUENCY: "Kiharu",
      PARTY: "UDA",
    },
    {
      "No.": 280,
      NAME: "Onyiego, Silvanus Osoro",
      CONSTITUENCY: "South Mugirango",
      PARTY: "UDA",
    },
    {
      "No.": 281,
      NAME: "Otucho, Mary Emaase",
      CONSTITUENCY: "Teso South",
      PARTY: "UDA",
    },
    {
      "No.": 282,
      NAME: "Pukose, Robert (Dr.)",
      CONSTITUENCY: "Endebess",
      PARTY: "UDA",
    },
    {
      "No.": 283,
      NAME: "Raso, Dido Ali",
      CONSTITUENCY: "Saku",
      PARTY: "UDA",
    },
    {
      "No.": 284,
      NAME: "Risa, Sunkuiya George",
      CONSTITUENCY: "Kajiado West",
      PARTY: "UDA",
    },
    {
      "No.": 285,
      NAME: "Robi, Mathias Nyamabe",
      CONSTITUENCY: "Kuria West",
      PARTY: "UDA",
    },
    {
      "No.": 286,
      NAME: "Rutto, Julius Kipletting",
      CONSTITUENCY: "Kesses",
      PARTY: "UDA",
    },
    {
      "No.": 287,
      NAME: "Saney, Ibrahim Abdi",
      CONSTITUENCY: "Wajir North",
      PARTY: "UDA",
    },
    {
      "No.": 288,
      NAME: "Sankaire, Leah Sopiato",
      CONSTITUENCY: "Kajiado (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 289,
      NAME: "Sergon, Flowrence Jematiah",
      CONSTITUENCY: "Baringo (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 290,
      NAME: "Shollei, Gladys Jepkosgei Boss",
      CONSTITUENCY: "Uasin Gishu (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 291,
      NAME: "Sigei, Francis Kipyegon arap",
      CONSTITUENCY: "Sotik",
      PARTY: "UDA",
    },
    {
      "No.": 292,
      NAME: "Sirma, Musa Cherutich",
      CONSTITUENCY: "Eldama Ravine",
      PARTY: "UDA",
    },
    {
      "No.": 293,
      NAME: "Sitati, Daniel Wanyama",
      CONSTITUENCY: "Webuye West",
      PARTY: "UDA",
    },
    {
      "No.": 294,
      NAME: "Sitienei, Janet Jepkemboi",
      CONSTITUENCY: "Turbo",
      PARTY: "UDA",
    },
    {
      "No.": 295,
      NAME: "Siyoi, Lillian Chebet",
      CONSTITUENCY: "Trans Nzoia (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 296,
      NAME: "Sudi, Oscar Kipchumba",
      CONSTITUENCY: "Kapseret",
      PARTY: "UDA",
    },
    {
      "No.": 297,
      NAME: "Tongoyo, Gabriel Koshal",
      CONSTITUENCY: "Narok West",
      PARTY: "UDA",
    },
    {
      "No.": 298,
      NAME: "Tonkei, Rebecca Noonaishi",
      CONSTITUENCY: "Narok (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 299,
      NAME: "Tonui, Joseph Kipkosgei",
      CONSTITUENCY: "Kuresoi South",
      PARTY: "UDA",
    },
    {
      "No.": 300,
      NAME: "Wachira, Rahab Mukami",
      CONSTITUENCY: "Nyeri (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 301,
      NAME: "Wainaina, Antony Njoroge",
      CONSTITUENCY: "Kieni",
      PARTY: "UDA",
    },
    {
      "No.": 302,
      NAME: "Wainaina, Michael Wambugu",
      CONSTITUENCY: "Othaya",
      PARTY: "UDA",
    },
    {
      "No.": 303,
      NAME: "Waithaka, John Machua",
      CONSTITUENCY: "Kiambu",
      PARTY: "UDA",
    },
    {
      "No.": 304,
      NAME: "Wamacukuru, James Githua Kamau",
      CONSTITUENCY: "Kabete",
      PARTY: "UDA",
    },
    {
      "No.": 305,
      NAME: "Wamuchomba, Gathoni",
      CONSTITUENCY: "Githunguri",
      PARTY: "UDA",
    },
    {
      "No.": 306,
      NAME: "John Njuguna",
      CONSTITUENCY: "Kiambaa",
      PARTY: "UDA",
    },
    {
      "No.": 307,
      NAME: "Wanjira, Martha Wangari",
      CONSTITUENCY: "Gilgil",
      PARTY: "UDA",
    },
    {
      "No.": 308,
      NAME: "Waqo, Naomi Jillo",
      CONSTITUENCY: "Marsabit (CWR)",
      PARTY: "UDA",
    },
    {
      "No.": 309,
      NAME: "Waweru, John Kiarie",
      CONSTITUENCY: "Dagoretti South",
      PARTY: "UDA",
    },
    {
      "No.": 310,
      NAME: "Yakub, Farah Salah",
      CONSTITUENCY: "Fafi",
      PARTY: "UDA",
    },
    {
      "No.": 311,
      NAME: "Yegon, Brighton Leonard",
      CONSTITUENCY: "Konoin",
      PARTY: "UDA",
    },
    {
      "No.": 312,
      NAME: "Yegon, Richard Kipkemoi",
      CONSTITUENCY: "Bomet East",
      PARTY: "UDA",
    },
    {
      "No.": 313,
      NAME: "Abdullahi, Bashir Sheikh",
      CONSTITUENCY: "Mandera North",
      PARTY: "UDM",
    },
    {
      "No.": 314,
      NAME: "Chiforomodo, Mangale Munga",
      CONSTITUENCY: "Lungalunga",
      PARTY: "UDM",
    },
    {
      "No.": 315,
      NAME: "Haro, Abdul Ebrahim",
      CONSTITUENCY: "Mandera South",
      PARTY: "UDM",
    },
    {
      "No.": 316,
      NAME: "Vacant",
      CONSTITUENCY: "Banissa",
    },
    {
      "No.": 317,
      NAME: "Harun, Suleka Hulbale",
      CONSTITUENCY: "Nominated",
      PARTY: "UDM",
    },
    {
      "No.": 318,
      NAME: "Lekuton, Joseph",
      CONSTITUENCY: "Laisamis",
      PARTY: "UDM",
    },
    {
      "No.": 319,
      NAME: "Sheikh, Umul Ker Kassim",
      CONSTITUENCY: "Mandera (CWR)",
      PARTY: "UDM",
    },
    {
      "No.": 320,
      NAME: "Yussuf, Adan Haji",
      CONSTITUENCY: "Mandera West",
      PARTY: "UDM",
    },
    {
      "No.": 321,
      NAME: "Onchoke Charles",
      CONSTITUENCY: "Bonchari",
      PARTY: "UPA",
    },
    {
      "No.": 322,
      NAME: "Jaldesa, Guyo Waqo",
      CONSTITUENCY: "Moyale",
      PARTY: "UPIA",
    },
    {
      "No.": 323,
      NAME: "Yakub, Adow Kuno",
      CONSTITUENCY: "Bura",
      PARTY: "UPIA",
    },
    {
      "No.": 324,
      NAME: "Abdi, Khamis Chome",
      CONSTITUENCY: "Voi",
      PARTY: "WDM",
    },
    {
      "No.": 325,
      NAME: "Aburi, Donya Dorice",
      CONSTITUENCY: "Kisii (CWR)",
      PARTY: "WDM",
    },
    {
      "No.": 326,
      NAME: "Basil, Robert Ngui",
      CONSTITUENCY: "Yatta",
      PARTY: "WDM",
    },
    {
      "No.": 327,
      NAME: "Bwire, John Okano",
      CONSTITUENCY: "Taveta",
      PARTY: "WDM",
    },
    {
      "No.": 328,
      NAME: "Kamene, Joyce",
      CONSTITUENCY: "Machakos (CWR)",
      PARTY: "WDM",
    },
    {
      "No.": 329,
      NAME: "Kasalu, Irene Muthoni",
      CONSTITUENCY: "Kitui (CWR)",
      PARTY: "WDM",
    },
    {
      "No.": 330,
      NAME: "Kiamba, Suzanne Ndunge",
      CONSTITUENCY: "Makueni",
      PARTY: "WDM",
    },
    {
      "No.": 331,
      NAME: "Kimilu, Joshua Kivinda",
      CONSTITUENCY: "Kaiti",
      PARTY: "WDM",
    },
    {
      "No.": 332,
      NAME: "King’ola Patrick Makau",
      CONSTITUENCY: "Mavoko",
      PARTY: "WDM",
    },
    {
      "No.": 333,
      NAME: "Maalim, Farah",
      CONSTITUENCY: "Dadaab",
      PARTY: "WDM",
    },
    {
      "No.": 334,
      NAME: "Mawathe, Julius Musili",
      CONSTITUENCY: "Embakasi South",
      PARTY: "WDM",
    },
    {
      "No.": 335,
      NAME: "Mbalu, Jessica Nduku Kiko",
      CONSTITUENCY: "Kibwezi East",
      PARTY: "WDM",
    },
    {
      "No.": 336,
      NAME: "Mboni, David Mwalika",
      CONSTITUENCY: "Kitui Rural",
      PARTY: "WDM",
    },
    {
      "No.": 337,
      NAME: "Mbui, Robert",
      CONSTITUENCY: "Kathiani",
      PARTY: "WDM",
    },
    {
      "No.": 338,
      NAME: "Momanyi, Innocent Obiri",
      CONSTITUENCY: "Bomachoge Borabu",
      PARTY: "WDM",
    },
    {
      "No.": 339,
      NAME: "Mule, Stephen Mutinda",
      CONSTITUENCY: "Matungulu",
      PARTY: "WDM",
    },
    {
      "No.": 340,
      NAME: "Mulu, Makali Benson",
      CONSTITUENCY: "Kitui Central",
      PARTY: "WDM",
    },
    {
      "No.": 341,
      NAME: "Mulyungi, Gideon Mutemi",
      CONSTITUENCY: "Mwingi Central",
      PARTY: "WDM",
    },
    {
      "No.": 342,
      NAME: "Mumo, Rose Museo",
      CONSTITUENCY: "Makueni (CWR)",
      PARTY: "WDM",
    },
    {
      "No.": 343,
      NAME: "Mwakuwona, Danson Mwashako",
      CONSTITUENCY: "Wundanyi",
      PARTY: "WDM",
    },
    {
      "No.": 344,
      NAME: "Nguna, Charles Ngusya",
      CONSTITUENCY: "Mwingi West",
      PARTY: "WDM",
    },
    {
      "No.": 345,
      NAME: "Nyenze, Edith Vethi",
      CONSTITUENCY: "Kitui West",
      PARTY: "WDM",
    },
    {
      "No.": 346,
      NAME: "Nzambia, Thudeeus Kithua",
      CONSTITUENCY: "Kilome",
      PARTY: "WDM",
    },
    {
      "No.": 347,
      NAME: "Nzengu, Paul Musyimi",
      CONSTITUENCY: "Mwingi North",
      PARTY: "WDM",
    },
    {
      "No.": 348,
      NAME: "Nzioka, Erastus Kivasu",
      CONSTITUENCY: "Mbooni",
      PARTY: "WDM",
    },
    {
      "No.": 349,
      NAME: "Twalib, Abubakar Ahmed",
      CONSTITUENCY: "Nominated",
      PARTY: "WDM",
    },
  ],
];
